#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <locale.h>
#include <conio.h>

//alterado timer//

void palavraFacil();
void palavraMedia();
void palavraDificil();
void wait(int seconds);
void mensagem();
void relogio(int tempo);
int  teste(int numero);

int vetorFacil[1000];
int vetorMedio[1000];
int vetorDificil[1000];
int posicao;

int main()
{
    setlocale(LC_ALL, "Portuguese");
    srand(time(NULL));

    unsigned int nivel;

    do{
        system("color 0F");
        printf("\n\n\n\n");
        printf("\t\t\tESCOLHA O NÍVEL DAS PALAVRAS\n\n");
        printf("\t\t\tDigite (1) para palavras fáceis\n\n");
        printf("\t\t\tDigite (2) para palavras médias\n\n");
        printf("\t\t\tDigite (3) para palavras difíceis\n\n");
        printf("\t\t\tResposta: ");
        scanf("%d",&nivel);
        system("cls");

        if(nivel == 1)
            palavraFacil();
        if(nivel == 2)
            palavraMedia();
        if(nivel == 3)
            palavraDificil();

    }while(nivel != 0);

}
void palavraFacil()
{
    int palavra;
    int i;
    system("color 2F");
    printf("\n\n\n\n");
    printf("\t\t\t   PALAVRAS FÁCEIS\n\n\n");
    for(i = 0; i < 13; i++)
    {
        palavra = rand() % 471;
        switch (palavra)
        {
            case 0: printf("\t\t\t\tACEITAR\n"); break;
            case 1: printf("\t\t\t\tAGENDA\n"); break;
            case 2: printf("\t\t\t\tAJUDAR\n"); break;
            case 3: printf("\t\t\t\tALUGUEL\n"); break;
            case 4: printf("\t\t\t\tARMÁRIO\n"); break;
            case 5: printf("\t\t\t\tATRASADO\n"); break;
            case 6: printf("\t\t\t\tBARRA\n"); break;
            case 7: printf("\t\t\t\tBAÚ\n"); break;
            case 8: printf("\t\t\t\tBEM\n"); break;
            case 9: printf("\t\t\t\tBERLIM\n"); break;
            case 10: printf("\t\t\t\tBRÓCOLIS\n"); break;
            case 11: printf("\t\t\t\tCACTO\n"); break;
            case 12: printf("\t\t\t\tCAIR\n"); break;
            case 13: printf("\t\t\t\tCAIXÃO\n"); break;
            case 14: printf("\t\t\t\tCAJU\n"); break;
            case 15: printf("\t\t\t\tCARA\n"); break;
            case 16: printf("\t\t\t\tCARIOCA\n"); break;
            case 17: printf("\t\t\t\tCASCAVEL\n"); break;
            case 18: printf("\t\t\t\tCATORZE\n"); break;
            case 19: printf("\t\t\t\tCEM\n"); break;
            case 20: printf("\t\t\t\tCÉU\n"); break;
            case 21: printf("\t\t\t\tCHÃO\n"); break;
            case 22: printf("\t\t\t\tCINCO\n"); break;
            case 23: printf("\t\t\t\tCOBRA\n"); break;
            case 24: printf("\t\t\t\tCOROA\n"); break;
            case 25: printf("\t\t\t\tCURITIBA\n"); break;
            case 26: printf("\t\t\t\tDADO\n"); break;
            case 27: printf("\t\t\t\tDAMA\n"); break;
            case 28: printf("\t\t\t\tDEZ\n"); break;
            case 29: printf("\t\t\t\tDEZESSEIS\n"); break;
            case 30: printf("\t\t\t\tDEZESSETE\n"); break;
            case 31: printf("\t\t\t\tDEZENOVE\n"); break;
            case 32: printf("\t\t\t\tDIÁRIO\n"); break;
            case 33: printf("\t\t\t\tDOIS\n"); break;
            case 34: printf("\t\t\t\tDOZE\n"); break;
            case 35: printf("\t\t\t\tDÚZIA\n"); break;
            case 36: printf("\t\t\t\tEINSTEIN\n"); break;
            case 37: printf("\t\t\t\tELE\n"); break;
            case 38: printf("\t\t\t\tFACEBOOK\n"); break;
            case 39: printf("\t\t\t\tFACULDADE\n"); break;
            case 40: printf("\t\t\t\tFALAR\n"); break;
            case 41: printf("\t\t\t\tFICAR\n"); break;
            case 42: printf("\t\t\t\tFIGURINHA\n"); break;
            case 43: printf("\t\t\t\tGALO\n"); break;
            case 44: printf("\t\t\t\tGRAMA\n"); break;
            case 45: printf("\t\t\t\tGRIPE\n"); break;
            case 46: printf("\t\t\t\tHORTELÃ\n"); break;
            case 47: printf("\t\t\t\tIGUAL\n"); break;
            case 48: printf("\t\t\t\tINFERNO\n"); break;
            case 49: printf("\t\t\t\tINGLÊS\n"); break;
            case 50: printf("\t\t\t\tJACARÉ\n"); break;
            case 51: printf("\t\t\t\tLAGARTO\n"); break;
            case 52: printf("\t\t\t\tLESMA\n"); break;
            case 53: printf("\t\t\t\tLULA\n"); break;
            case 54: printf("\t\t\t\tMENTA\n"); break;
            case 55: printf("\t\t\t\tMENTIRA\n"); break;
            case 56: printf("\t\t\t\tMENINA\n"); break;
            case 57: printf("\t\t\t\tMENINO\n"); break;
            case 58: printf("\t\t\t\tNATAL\n"); break;
            case 59: printf("\t\t\t\tNAZISMO\n"); break;
            case 60: printf("\t\t\t\tNENHUM\n"); break;
            case 61: printf("\t\t\t\tNONO\n"); break;
            case 62: printf("\t\t\t\tNU\n"); break;
            case 63: printf("\t\t\t\tNÚCLEO\n"); break;
            case 64: printf("\t\t\t\tOITAVO\n"); break;
            case 65: printf("\t\t\t\tONZE\n"); break;
            case 66: printf("\t\t\t\tPAREDE\n"); break;
            case 67: printf("\t\t\t\tPASSIVO\n"); break;
            case 68: printf("\t\t\t\tPEGAR\n"); break;
            case 69: printf("\t\t\t\tPÊNIS\n"); break;
            case 70: printf("\t\t\t\tPESSOA\n"); break;
            case 71: printf("\t\t\t\tPROIBIDO\n"); break;
            case 72: printf("\t\t\t\tRAIVA\n"); break;
            case 73: printf("\t\t\t\tSAÍDA\n"); break;
            case 74: printf("\t\t\t\tSATÉLITE\n"); break;
            case 75: printf("\t\t\t\tSEIS\n"); break;
            case 76: printf("\t\t\t\tSEMANA\n"); break;
            case 77: printf("\t\t\t\tTETO\n"); break;
            case 78: printf("\t\t\t\tTRÂNSITO\n"); break;
            case 79: printf("\t\t\t\tTREZE\n"); break;
            case 80: printf("\t\t\t\tVAGINA\n"); break;
            case 81: printf("\t\t\t\tVENTILADOR\n"); break;
            case 82: printf("\t\t\t\tVERTICAL\n"); break;
            case 83: printf("\t\t\t\tVÍRUS\n"); break;
            case 84: printf("\t\t\t\tXAMPU\n"); break;
            case 85: printf("\t\t\t\tZEBRA\n"); break;
            case 86: printf("\t\t\t\tZELADOR\n"); break;
            case 87: printf("\t\t\t\tCASA\n"); break;
            case 88: printf("\t\t\t\tSECUNDÁRIO\n"); break;
            case 89: printf("\t\t\t\tASSISTIR\n"); break;
            case 90: printf("\t\t\t\tPRIMÁRIO\n"); break;
            case 91: printf("\t\t\t\tMÁ\n"); break;
            case 92: printf("\t\t\t\tBOA\n"); break;
            case 93: printf("\t\t\t\tPAPAGAIO\n"); break;
            case 94: printf("\t\t\t\tAZAR\n"); break;
            case 95: printf("\t\t\t\tÁCIDO\n"); break;
            case 96: printf("\t\t\t\tBATALHA\n"); break;
            case 97: printf("\t\t\t\tPRESENTE\n"); break;
            case 98: printf("\t\t\t\tGRÉCIA\n"); break;
            case 99: printf("\t\t\t\tLIGAR\n"); break;
            case 100: printf("\t\t\t\tRECUSAR\n"); break;
            case 101: printf("\t\t\t\tAMAZÔNIA\n"); break;
            case 102: printf("\t\t\t\tMANAUS\n"); break;
            case 103: printf("\t\t\t\tMAIORIA\n"); break;
            case 104: printf("\t\t\t\tMEGA\n"); break;
            case 105: printf("\t\t\t\tCAUDA\n"); break;
            case 106: printf("\t\t\t\tMELECA\n"); break;
            case 107: printf("\t\t\t\tOITENTA\n"); break;
            case 108: printf("\t\t\t\tLÍDER\n"); break;
            case 109: printf("\t\t\t\tESTACIONAMENTO\n"); break;
            case 110: printf("\t\t\t\tTIPO\n"); break;
            case 111: printf("\t\t\t\tZERO\n"); break;
            case 112: printf("\t\t\t\tÁUDIO\n"); break;
            case 113: printf("\t\t\t\tINSETO\n"); break;
            case 114: printf("\t\t\t\tAVE\n"); break;
            case 115: printf("\t\t\t\tCHATO\n"); break;
            case 116: printf("\t\t\t\tESPIGA\n"); break;
            case 117: printf("\t\t\t\tÁSIA\n"); break;
            case 118: printf("\t\t\t\tTIME\n"); break;
            case 119: printf("\t\t\t\tCEM\n"); break;
            case 120: printf("\t\t\t\tDUZENTOS\n"); break;
            case 121: printf("\t\t\t\tTREZENTOS\n"); break;
            case 122: printf("\t\t\t\tQUATROCENTOS\n"); break;
            case 123: printf("\t\t\t\tQUINHENTOS\n"); break;
            case 124: printf("\t\t\t\tSEISCENTOS\n"); break;
            case 125: printf("\t\t\t\tSETECENTOS\n"); break;
            case 126: printf("\t\t\t\tOITOCENTOS\n"); break;
            case 127: printf("\t\t\t\tNOVECENTOS\n"); break;
            case 128: printf("\t\t\t\tDUZENTOS\n"); break;
            case 129: printf("\t\t\t\tMIL\n"); break;
            case 130: printf("\t\t\t\tMILHÃO\n"); break;
            case 131: printf("\t\t\t\tBILHÃO\n"); break;
            case 132: printf("\t\t\t\tTRILHÃO\n"); break;
            case 133: printf("\t\t\t\tINDICADOR\n"); break;
            case 134: printf("\t\t\t\tMINDINHO\n"); break;
            case	135	:	printf("\t\t\t	ABACATE	\n"); break;
            case	136	:	printf("\t\t\t	ABACAXI	\n"); break;
            case	137	:	printf("\t\t\t	ACIMA	\n"); break;
            case	138	:	printf("\t\t\t	ACORDADO	\n"); break;
            case	139	:	printf("\t\t\t	AÇÚCAR	\n"); break;
            case	140	:	printf("\t\t\t	AEROPORTO	\n"); break;
            case	141	:	printf("\t\t\t	ÁFRICA	\n"); break;
            case	142	:	printf("\t\t\t	ÁGUA	\n"); break;
            case	143	:	printf("\t\t\t	ALMOÇO	\n"); break;
            case	144	:	printf("\t\t\t	ALTO	\n"); break;
            case	145	:	printf("\t\t\t	AMARELO	\n"); break;
            case	146	:	printf("\t\t\t	AMOR	\n"); break;
            case	147	:	printf("\t\t\t	ANEL	\n"); break;
            case	148	:	printf("\t\t\t	ANIVERSÁRIO	\n"); break;
            case	149	:	printf("\t\t\t	ANTERIOR	\n"); break;
            case	150	:	printf("\t\t\t	APRENDER	\n"); break;
            case	151	:	printf("\t\t\t	APROXIMAR	\n"); break;
            case	152	:	printf("\t\t\t	ARANHA	\n"); break;
            case	153	:	printf("\t\t\t	ARROZ	\n"); break;
            case	154	:	printf("\t\t\t	ÁRVORE	\n"); break;
            case	155	:	printf("\t\t\t	ASSADO	\n"); break;
            case	156	:	printf("\t\t\t	ASSUSTAR	\n"); break;
            case	157	:	printf("\t\t\t	ATAQUE	\n"); break;
            case	158	:	printf("\t\t\t	ATENÇÃO	\n"); break;
            case	159	:	printf("\t\t\t	ATRASADO	\n"); break;
            case	160	:	printf("\t\t\t	AUTOMÁTICO	\n"); break;
            case	161	:	printf("\t\t\t	AVENIDA	\n"); break;
            case	162	:	printf("\t\t\t	BAIXO	\n"); break;
            case	163	:	printf("\t\t\t	BARBA	\n"); break;
            case	164	:	printf("\t\t\t	BARULHO	\n"); break;
            case	165	:	printf("\t\t\t	BIGODE	\n"); break;
            case	166	:	printf("\t\t\t	BISCOITO	\n"); break;
            case	167	:	printf("\t\t\t	BOCA	\n"); break;
            case	168	:	printf("\t\t\t	BOM	\n"); break;
            case	169	:	printf("\t\t\t	BONECA	\n"); break;
            case	170	:	printf("\t\t\t	BONITO	\n"); break;
            case	171	:	printf("\t\t\t	BORRACHA	\n"); break;
            case	172	:	printf("\t\t\t	BRAÇO	\n"); break;
            case	173	:	printf("\t\t\t	BRANCO	\n"); break;
            case	174	:	printf("\t\t\t	BRIGADEIRO	\n"); break;
            case	175	:	printf("\t\t\t	TOMATE	\n"); break;
            case	176	:	printf("\t\t\t	BURRO	\n"); break;
            case	177	:	printf("\t\t\t	TORTA	\n"); break;
            case	178	:	printf("\t\t\t	CABELO	\n"); break;
            case	179	:	printf("\t\t\t	CACHORRO	\n"); break;
            case	180	:	printf("\t\t\t	CALÇA	\n"); break;
            case	181	:	printf("\t\t\t	CAMINHÃO	\n"); break;
            case	182	:	printf("\t\t\t	CANETA	\n"); break;
            case	183	:	printf("\t\t\t	CAPACETE	\n"); break;
            case	184	:	printf("\t\t\t	CARANGUEJO	\n"); break;
            case	185	:	printf("\t\t\t	CARTA	\n"); break;
            case	186	:	printf("\t\t\t	CASADO	\n"); break;
            case	187	:	printf("\t\t\t	CAVALO	\n"); break;
            case	188	:	printf("\t\t\t	CEBOLA	\n"); break;
            case	189	:	printf("\t\t\t	TOALHA	\n"); break;
            case	190	:	printf("\t\t\t	CEGO	\n"); break;
            case	191	:	printf("\t\t\t	TRIÂNGULO	\n"); break;
            case	192	:	printf("\t\t\t	CELULAR	\n"); break;
            case	193	:	printf("\t\t\t	DÉCIMO	\n"); break;
            case	194	:	printf("\t\t\t	DEFENDER	\n"); break;
            case	195	:	printf("\t\t\t	DEFESA	\n"); break;
            case	196	:	printf("\t\t\t	DEZEMBRO	\n"); break;
            case	197	:	printf("\t\t\t	DEZOITO	\n"); break;
            case	198	:	printf("\t\t\t	DIANTEIRO	\n"); break;
            case	199	:	printf("\t\t\t	DIFERENTE	\n"); break;
            case	200	:	printf("\t\t\t	DIFÍCIL	\n"); break;
            case	201	:	printf("\t\t\t	DINHEIRO	\n"); break;
            case	202	:	printf("\t\t\t	DIVISÃO	\n"); break;
            case	203	:	printf("\t\t\t	DIVÓRCIO	\n"); break;
            case	204	:	printf("\t\t\t	DORMIR	\n"); break;
            case	205	:	printf("\t\t\t	DRAGÃO	\n"); break;
            case	206	:	printf("\t\t\t	ÉGUA	\n"); break;
            case	207	:	printf("\t\t\t	ENCONTRAR	\n"); break;
            case	208	:	printf("\t\t\t	ERRADO	\n"); break;
            case	209	:	printf("\t\t\t	ESCOLA	\n"); break;
            case	210	:	printf("\t\t\t	ESCURO	\n"); break;
            case	211	:	printf("\t\t\t	ESPADA	\n"); break;
            case	212	:	printf("\t\t\t	ESPOSA	\n"); break;
            case	213	:	printf("\t\t\t	ESQUERDA	\n"); break;
            case	214	:	printf("\t\t\t	ESTRELA	\n"); break;
            case	215	:	printf("\t\t\t	FACA	\n"); break;
            case	216	:	printf("\t\t\t	FÁCIL	\n"); break;
            case	217	:	printf("\t\t\t	FAMÍLIA	\n"); break;
            case	218	:	printf("\t\t\t	FANTASMA	\n"); break;
            case	219	:	printf("\t\t\t	FARAÓ	\n"); break;
            case	220	:	printf("\t\t\t	FECHADO	\n"); break;
            case	221	:	printf("\t\t\t	FEIJÃO	\n"); break;
            case	222	:	printf("\t\t\t	FEIO	\n"); break;
            case	223	:	printf("\t\t\t	FELIZ	\n"); break;
            case	224	:	printf("\t\t\t	FERRADURA	\n"); break;
            case	225	:	printf("\t\t\t	FERRO	\n"); break;
            case	226	:	printf("\t\t\t	FILHO	\n"); break;
            case	227	:	printf("\t\t\t	FLOR	\n"); break;
            case	228	:	printf("\t\t\t	FLORESTA	\n"); break;
            case	229	:	printf("\t\t\t	FORÇA	\n"); break;
            case	230	:	printf("\t\t\t	FOTO	\n"); break;
            case	231	:	printf("\t\t\t	FRIO	\n"); break;
            case	232	:	printf("\t\t\t	FRITO	\n"); break;
            case	233	:	printf("\t\t\t	FUTEBOL	\n"); break;
            case	234	:	printf("\t\t\t	FUTURO	\n"); break;
            case	235	:	printf("\t\t\t	GANHAR	\n"); break;
            case	236	:	printf("\t\t\t	GARFO	\n"); break;
            case	237	:	printf("\t\t\t	GAROTO	\n"); break;
            case	238	:	printf("\t\t\t	GARRAFA	\n"); break;
            case	239	:	printf("\t\t\t	GASOLINA	\n"); break;
            case	240	:	printf("\t\t\t	GATO	\n"); break;
            case	241	:	printf("\t\t\t	GELO	\n"); break;
            case	242	:	printf("\t\t\t	GEOGRAFIA	\n"); break;
            case	243	:	printf("\t\t\t	GIGANTE	\n"); break;
            case	244	:	printf("\t\t\t	GIRAFA	\n"); break;
            case	245	:	printf("\t\t\t	GIRASSOL	\n"); break;
            case	246	:	printf("\t\t\t	GORILA	\n"); break;
            case	247	:	printf("\t\t\t	GOSTAR	\n"); break;
            case	248	:	printf("\t\t\t	GOVERNADOR	\n"); break;
            case	249	:	printf("\t\t\t	GUARANÁ	\n"); break;
            case	250	:	printf("\t\t\t	GUERRA	\n"); break;
            case	251	:	printf("\t\t\t	HERÓI	\n"); break;
            case	252	:	printf("\t\t\t	HOMEM	\n"); break;
            case	253	:	printf("\t\t\t	VIDA	\n"); break;
            case	254	:	printf("\t\t\t	VÍDEO	\n"); break;
            case	255	:	printf("\t\t\t	VIDRO	\n"); break;
            case	256	:	printf("\t\t\t	VILÃO	\n"); break;
            case	257	:	printf("\t\t\t	VINHO	\n"); break;
            case	258	:	printf("\t\t\t	VIOLETA	\n"); break;
            case	259	:	printf("\t\t\t	VIRGEM	\n"); break;
            case	260	:	printf("\t\t\t	VÍRGULA	\n"); break;
            case	261	:	printf("\t\t\t	VOCÊ	\n"); break;
            case	262	:	printf("\t\t\t	VÔLEI	\n"); break;
            case	263	:	printf("\t\t\t	IGREJA	\n"); break;
            case	264	:	printf("\t\t\t	IMORTAL	\n"); break;
            case	265	:	printf("\t\t\t	INGLATERRA	\n"); break;
            case	266	:	printf("\t\t\t	INGREDIENTE	\n"); break;
            case	267	:	printf("\t\t\t	INÍCIO	\n"); break;
            case	268	:	printf("\t\t\t	INOCENTE	\n"); break;
            case	269	:	printf("\t\t\t	INTELIGENTE	\n"); break;
            case	270	:	printf("\t\t\t	INVERNO	\n"); break;
            case	271	:	printf("\t\t\t	IRMÃO	\n"); break;
            case	272	:	printf("\t\t\t	MOCHILA	\n"); break;
            case	273	:	printf("\t\t\t	MOEDA	\n"); break;
            case	274	:	printf("\t\t\t	MOLE	\n"); break;
            case	275	:	printf("\t\t\t	MORANGO	\n"); break;
            case	276	:	printf("\t\t\t	MOSTARDA	\n"); break;
            case	277	:	printf("\t\t\t	MUDO	\n"); break;
            case	278	:	printf("\t\t\t	MULHER	\n"); break;
            case	279	:	printf("\t\t\t	MUNDO	\n"); break;
            case	280	:	printf("\t\t\t	MÚSICA	\n"); break;
            case	281	:	printf("\t\t\t	JANEIRO	\n"); break;
            case	282	:	printf("\t\t\t	JAPONÊS	\n"); break;
            case	283	:	printf("\t\t\t	JOELHO	\n"); break;
            case	284	:	printf("\t\t\t	JOVEM	\n"); break;
            case	285	:	printf("\t\t\t	JUDEU	\n"); break;
            case	286	:	printf("\t\t\t	JULHO	\n"); break;
            case	287	:	printf("\t\t\t	JÚPITER	\n"); break;
            case	288	:	printf("\t\t\t	POLICIAL	\n"); break;
            case	289	:	printf("\t\t\t	POLVO	\n"); break;
            case	290	:	printf("\t\t\t	PORTA	\n"); break;
            case	291	:	printf("\t\t\t	PORTO	\n"); break;
            case	292	:	printf("\t\t\t	POSTERIOR	\n"); break;
            case	293	:	printf("\t\t\t	POUCO	\n"); break;
            case	294	:	printf("\t\t\t	PRAÇA	\n"); break;
            case	295	:	printf("\t\t\t	PRAIA	\n"); break;
            case	296	:	printf("\t\t\t	CENTRO	\n"); break;
            case	297	:	printf("\t\t\t	CEREJA	\n"); break;
            case	298	:	printf("\t\t\t	CERTO	\n"); break;
            case	299	:	printf("\t\t\t	CERVEJA	\n"); break;
            case	300	:	printf("\t\t\t	CHEGADA	\n"); break;
            case	301	:	printf("\t\t\t	CHEIROSO	\n"); break;
            case	302	:	printf("\t\t\t	CHUVA	\n"); break;
            case	303	:	printf("\t\t\t	CÍRCULO	\n"); break;
            case	304	:	printf("\t\t\t	CINZA	\n"); break;
            case	305	:	printf("\t\t\t	CIRCO	\n"); break;
            case	306	:	printf("\t\t\t	COELHO	\n"); break;
            case	307	:	printf("\t\t\t	COLHER	\n"); break;
            case	308	:	printf("\t\t\t	COMER	\n"); break;
            case	309	:	printf("\t\t\t	LAGOA	\n"); break;
            case	310	:	printf("\t\t\t	LANTERNA	\n"); break;
            case	311	:	printf("\t\t\t	LÁPIS	\n"); break;
            case	312	:	printf("\t\t\t	LARANJA	\n"); break;
            case	313	:	printf("\t\t\t	LEÃO	\n"); break;
            case	314	:	printf("\t\t\t	LEGAL	\n"); break;
            case	315	:	printf("\t\t\t	LEITE	\n"); break;
            case	316	:	printf("\t\t\t	LEMBRAR	\n"); break;
            case	317	:	printf("\t\t\t	LEVANTAR	\n"); break;
            case	318	:	printf("\t\t\t	LIBERTAR	\n"); break;
            case	319	:	printf("\t\t\t	LIMÃO	\n"); break;
            case	320	:	printf("\t\t\t	LIMPO	\n"); break;
            case	321	:	printf("\t\t\t	LÍNGUA	\n"); break;
            case	322	:	printf("\t\t\t	LIVRO	\n"); break;
            case	323	:	printf("\t\t\t	LOBO	\n"); break;
            case	324	:	printf("\t\t\t	TERRA	\n"); break;
            case	325	:	printf("\t\t\t	LONDRES	\n"); break;
            case	326	:	printf("\t\t\t	LONGO	\n"); break;
            case	327	:	printf("\t\t\t	LOUCO	\n"); break;
            case	328	:	printf("\t\t\t	LUA	\n"); break;
            case	329	:	printf("\t\t\t	LUVA	\n"); break;
            case	330	:	printf("\t\t\t	LUZ	\n"); break;
            case	331	:	printf("\t\t\t	MACARRÃO	\n"); break;
            case	332	:	printf("\t\t\t	MAIONESE	\n"); break;
            case	333	:	printf("\t\t\t	MÃE	\n"); break;
            case	334	:	printf("\t\t\t	MALDADE	\n"); break;
            case	335	:	printf("\t\t\t	MALUCO	\n"); break;
            case	336	:	printf("\t\t\t	VERDE	\n"); break;
            case	337	:	printf("\t\t\t	VERMELHO	\n"); break;
            case	338	:	printf("\t\t\t	MANHÃ	\n"); break;
            case	339	:	printf("\t\t\t	MANTEIGA	\n"); break;
            case	340	:	printf("\t\t\t	MANSÃO	\n"); break;
            case	341	:	printf("\t\t\t	MANUAL	\n"); break;
            case	342	:	printf("\t\t\t	MAR	\n"); break;
            case	343	:	printf("\t\t\t	MARTELO	\n"); break;
            case	344	:	printf("\t\t\t	MASCULINO	\n"); break;
            case	345	:	printf("\t\t\t	MATEMÁTICA	\n"); break;
            case	346	:	printf("\t\t\t	MECÂNICO	\n"); break;
            case	347	:	printf("\t\t\t	MÉDICO	\n"); break;
            case	348	:	printf("\t\t\t	MELANCIA	\n"); break;
            case	349	:	printf("\t\t\t	MENOS	\n"); break;
            case	350	:	printf("\t\t\t	MESA	\n"); break;
            case	351	:	printf("\t\t\t	TIGRE	\n"); break;
            case	352	:	printf("\t\t\t	MILHO	\n"); break;
            case	353	:	printf("\t\t\t	MINEIRO	\n"); break;
            case	354	:	printf("\t\t\t	MINHOCA	\n"); break;
            case	355	:	printf("\t\t\t	MINÚSCULO	\n"); break;
            case	356	:	printf("\t\t\t	NARIZ	\n"); break;
            case	357	:	printf("\t\t\t	NAVIO	\n"); break;
            case	358	:	printf("\t\t\t	NETO	\n"); break;
            case	359	:	printf("\t\t\t	NORTE	\n"); break;
            case	360	:	printf("\t\t\t	PRATA	\n"); break;
            case	361	:	printf("\t\t\t	PRÉDIO	\n"); break;
            case	362	:	printf("\t\t\t	PREFEITO	\n"); break;
            case	363	:	printf("\t\t\t	TRÊS	\n"); break;
            case	364	:	printf("\t\t\t	PRENDER	\n"); break;
            case	365	:	printf("\t\t\t	PRESIDENTE	\n"); break;
            case	366	:	printf("\t\t\t	PRESUNTO	\n"); break;
            case	367	:	printf("\t\t\t	PRETO	\n"); break;
            case	368	:	printf("\t\t\t	TRISTE	\n"); break;
            case	369	:	printf("\t\t\t	PRIMAVERA	\n"); break;
            case	370	:	printf("\t\t\t	PROFESSOR	\n"); break;
            case	371	:	printf("\t\t\t	PROGRAMA	\n"); break;
            case	372	:	printf("\t\t\t	TUBARÃO	\n"); break;
            case	373	:	printf("\t\t\t	PRÓXIMO	\n"); break;
            case	374	:	printf("\t\t\t	ÓCULOS	\n"); break;
            case	375	:	printf("\t\t\t	OESTE	\n"); break;
            case	376	:	printf("\t\t\t	OMBRO	\n"); break;
            case	377	:	printf("\t\t\t	ONTEM	\n"); break;
            case	378	:	printf("\t\t\t	ORELHA	\n"); break;
            case	379	:	printf("\t\t\t	OSSO	\n"); break;
            case	380	:	printf("\t\t\t	OURO	\n"); break;
            case	381	:	printf("\t\t\t	OUTONO	\n"); break;
            case	382	:	printf("\t\t\t	OUTUBRO	\n"); break;
            case	383	:	printf("\t\t\t	OVO	\n"); break;
            case	384	:	printf("\t\t\t	CONSERTAR	\n"); break;
            case	385	:	printf("\t\t\t	COPO	\n"); break;
            case	386	:	printf("\t\t\t	CORAÇÃO	\n"); break;
            case	387	:	printf("\t\t\t	CORAJOSO	\n"); break;
            case	388	:	printf("\t\t\t	CORTINA	\n"); break;
            case	389	:	printf("\t\t\t	COVARDE	\n"); break;
            case	390	:	printf("\t\t\t	CRÉDITO	\n"); break;
            case	391	:	printf("\t\t\t	CRIANÇA	\n"); break;
            case	392	:	printf("\t\t\t	CULPADO	\n"); break;
            case	393	:	printf("\t\t\t	PACÍFICO	\n"); break;
            case	394	:	printf("\t\t\t	PADRASTO	\n"); break;
            case	395	:	printf("\t\t\t	PAI	\n"); break;
            case	396	:	printf("\t\t\t	PANELA	\n"); break;
            case	397	:	printf("\t\t\t	PAPEL	\n"); break;
            case	398	:	printf("\t\t\t	PARIS	\n"); break;
            case	399	:	printf("\t\t\t	PÁSCOA	\n"); break;
            case	400	:	printf("\t\t\t	PATO	\n"); break;
            case	401	:	printf("\t\t\t	PEIXE	\n"); break;
            case	402	:	printf("\t\t\t	PELE	\n"); break;
            case	403	:	printf("\t\t\t	PENA	\n"); break;
            case	404	:	printf("\t\t\t	PEQUENO	\n"); break;
            case	405	:	printf("\t\t\t	PERNA	\n"); break;
            case	406	:	printf("\t\t\t	PESADELO	\n"); break;
            case	407	:	printf("\t\t\t	PESCOÇO	\n"); break;
            case	408	:	printf("\t\t\t	TÊNIS	\n"); break;
            case	409	:	printf("\t\t\t	PICOLÉ	\n"); break;
            case	410	:	printf("\t\t\t	PILHA	\n"); break;
            case	411	:	printf("\t\t\t	PINGUIM	\n"); break;
            case	412	:	printf("\t\t\t	PNEU	\n"); break;
            case	413	:	printf("\t\t\t	QUADRADO	\n"); break;
            case	414	:	printf("\t\t\t	QUARTO	\n"); break;
            case	415	:	printf("\t\t\t	QUEIJO	\n"); break;
            case	416	:	printf("\t\t\t	QUENTE	\n"); break;
            case	417	:	printf("\t\t\t	QUINTO	\n"); break;
            case	418	:	printf("\t\t\t	QUINZE	\n"); break;
            case	419	:	printf("\t\t\t	TABELA	\n"); break;
            case	420	:	printf("\t\t\t	UVA	\n"); break;
            case	421	:	printf("\t\t\t	TARTARUGA	\n"); break;
            case	422	:	printf("\t\t\t	UM	\n"); break;
            case	423	:	printf("\t\t\t	VERDADE	\n"); break;
            case	424	:	printf("\t\t\t	VELHO	\n"); break;
            case	425	:	printf("\t\t\t	VENDA	\n"); break;
            case	426	:	printf("\t\t\t	RÃ	\n"); break;
            case	427	:	printf("\t\t\t	RAINHA	\n"); break;
            case	428	:	printf("\t\t\t	RATO	\n"); break;
            case	429	:	printf("\t\t\t	REFRIGERANTE	\n"); break;
            case	430	:	printf("\t\t\t	RICO	\n"); break;
            case	431	:	printf("\t\t\t	RIM	\n"); break;
            case	432	:	printf("\t\t\t	RIQUEZA	\n"); break;
            case	433	:	printf("\t\t\t	ROBÔ	\n"); break;
            case	434	:	printf("\t\t\t	RODA	\n"); break;
            case	435	:	printf("\t\t\t	RODOVIÁRIA	\n"); break;
            case	436	:	printf("\t\t\t	ROMA	\n"); break;
            case	437	:	printf("\t\t\t	ROSA	\n"); break;
            case	438	:	printf("\t\t\t	ROSTO	\n"); break;
            case	439	:	printf("\t\t\t	ROUBO	\n"); break;
            case	440	:	printf("\t\t\t	ROXO	\n"); break;
            case	441	:	printf("\t\t\t	RUA	\n"); break;
            case	442	:	printf("\t\t\t	RÚSSIA	\n"); break;
            case	443	:	printf("\t\t\t	SÁBADO	\n"); break;
            case	444	:	printf("\t\t\t	SALGADO	\n"); break;
            case	445	:	printf("\t\t\t	SANGUE	\n"); break;
            case	446	:	printf("\t\t\t	SAPATO	\n"); break;
            case	447	:	printf("\t\t\t	SAPO	\n"); break;
            case	448	:	printf("\t\t\t	SATURNO	\n"); break;
            case	449	:	printf("\t\t\t	SEDE	\n"); break;
            case	450	:	printf("\t\t\t	SEMPRE	\n"); break;
            case	451	:	printf("\t\t\t	TELEFONE	\n"); break;
            case	452	:	printf("\t\t\t	SERPENTE	\n"); break;
            case	453	:	printf("\t\t\t	SETE	\n"); break;
            case	454	:	printf("\t\t\t	SETEMBRO	\n"); break;
            case	455	:	printf("\t\t\t	SILÊNCIO	\n"); break;
            case	456	:	printf("\t\t\t	SOBREMESA	\n"); break;
            case	457	:	printf("\t\t\t	SOBRINHO	\n"); break;
            case	458	:	printf("\t\t\t	SOGRA	\n"); break;
            case	459	:	printf("\t\t\t	SOLDADO	\n"); break;
            case	460	:	printf("\t\t\t	SÓLIDO	\n"); break;
            case	461	:	printf("\t\t\t	SOLTEIRO	\n"); break;
            case	462	:	printf("\t\t\t	SOLTO	\n"); break;
            case	463	:	printf("\t\t\t	SONHO	\n"); break;
            case	464	:	printf("\t\t\t	SORTE	\n"); break;
            case	465	:	printf("\t\t\t	SORVETE	\n"); break;
            case	466	:	printf("\t\t\t	SOZINHO	\n"); break;
            case	467	:	printf("\t\t\t	SUCESSO	\n"); break;
            case	468	:	printf("\t\t\t	SUL	\n"); break;
            case	469	:	printf("\t\t\t	SUMIR	\n"); break;
            case	470	:	printf("\t\t\t	SUTIÃ	\n"); break;

        }
    }
    printf("\n\n\n\n");
    relogio(40);
    printf("\a");
    system("cls");
    mensagem();
}
void palavraMedia()
{
    int palavra;
    int i;
    system("color 6F");
    printf("\n\n\n\n");
    printf("\t\t\t   PALAVRAS MEDIAS\n\n\n");

    for(i = 0; i < 9; i++)
    {
        palavra = rand() % 741;
        switch (palavra)
        {
            case 0: printf("\t\t\t\tACAREJO\n"); break;
            case 1: printf("\t\t\t\tCALVÍCIE\n"); break;
            case 2: printf("\t\t\t\tCAPITALISMO\n"); break;
            case 3: printf("\t\t\t\tCARRETA\n"); break;
            case 4: printf("\t\t\t\tCASTIÇAL\n"); break;
            case 5: printf("\t\t\t\tCERTEZA\n"); break;
            case 6: printf("\t\t\t\tCESARIANA\n"); break;
            case 7: printf("\t\t\t\tACEROLA\n"); break;
            case 8: printf("\t\t\t\tAGUENTAR\n"); break;
            case 9: printf("\t\t\t\tÁLBUM\n"); break;
            case 10: printf("\t\t\t\tALCATÉIA\n"); break;
            case 11: printf("\t\t\t\tANACONDA\n"); break;
            case 12: printf("\t\t\t\tAPLICATIVO\n"); break;
            case 13: printf("\t\t\t\tARACNÍDEO\n"); break;
            case 14: printf("\t\t\t\tARENA\n"); break;
            case 15: printf("\t\t\t\tASSUMIR\n"); break;
            case 16: printf("\t\t\t\tDAMASCO\n"); break;
            case 17: printf("\t\t\t\tDETONAR\n"); break;
            case 18: printf("\t\t\t\tDROMEDÁRIO\n"); break;
            case 19: printf("\t\t\t\tEGOÍSTA\n"); break;
            case 20: printf("\t\t\t\tEIXO\n"); break;
            case 21: printf("\t\t\t\tELETRICIDADE\n"); break;
            case 22: printf("\t\t\t\tELOGIO\n"); break;
            case 23: printf("\t\t\t\tENORME\n"); break;
            case 24: printf("\t\t\t\tEPIDEMIA\n"); break;
            case 25: printf("\t\t\t\tESFEROGRÁFICA\n"); break;
            case 26: printf("\t\t\t\tESQUISITO\n"); break;
            case 27: printf("\t\t\t\tESTRELA-DO-MAR\n"); break;
            case 28: printf("\t\t\t\tESTRESSADO\n"); break;
            case 29: printf("\t\t\t\tEGOÍSTA\n"); break;
            case 30: printf("\t\t\t\tEIXO\n"); break;
            case 31: printf("\t\t\t\tELETRICIDADE\n"); break;
            case 32: printf("\t\t\t\tELOGIO\n"); break;
            case 33: printf("\t\t\t\tENORME\n"); break;
            case 34: printf("\t\t\t\tEPIDEMIA\n"); break;
            case 35: printf("\t\t\t\tESFEROGRÁFICA\n"); break;
            case 36: printf("\t\t\t\tESQUISITO\n"); break;
            case 37: printf("\t\t\t\tESTRELA-DO-MAR\n"); break;
            case 39: printf("\t\t\t\tESTRESSADO\n"); break;
            case 40: printf("\t\t\t\tCACAREJO\n"); break;
            case 41: printf("\t\t\t\tCALVÍCIE\n"); break;
            case 42: printf("\t\t\t\tCAPITALISMO\n"); break;
            case 43: printf("\t\t\t\tCARDUME\n"); break;
            case 44: printf("\t\t\t\tCARRETA\n"); break;
            case 45: printf("\t\t\t\tCASTIÇAL\n"); break;
            case 46: printf("\t\t\t\tCERTEZA\n"); break;
            case 47: printf("\t\t\t\tCESARIANA\n"); break;
            case 48: printf("\t\t\t\tCHULÉ\n"); break;
            case 49: printf("\t\t\t\tCIRURGIA\n"); break;
            case 50: printf("\t\t\t\tCOFRE\n"); break;
            case 51: printf("\t\t\t\tCÓLICA\n"); break;
            case 52: printf("\t\t\t\tCOLOMBO\n"); break;
            case 53: printf("\t\t\t\tCOMUNICADO\n"); break;
            case 54: printf("\t\t\t\tCONFESSIONÁRIO\n"); break;
            case 55: printf("\t\t\t\tCONSTELAÇÃO\n"); break;
            case 56: printf("\t\t\t\tCONVERSA\n"); break;
            case 57: printf("\t\t\t\tCOQUETEL\n"); break;
            case 58: printf("\t\t\t\tCOURO\n"); break;
            case 59: printf("\t\t\t\tCRAVO\n"); break;
            case 60: printf("\t\t\t\tCROCODILO\n"); break;
            case 61: printf("\t\t\t\tCURITR\n"); break;
            case 62: printf("\t\t\t\tFAZER\n"); break;
            case 63: printf("\t\t\t\tFERRUGEM\n"); break;
            case 64: printf("\t\t\t\tFIADO\n"); break;
            case 65: printf("\t\t\t\tFILHOTE\n"); break;
            case 66: printf("\t\t\t\tFLAMENGO\n"); break;
            case 67: printf("\t\t\t\tFLORIANÓPOLIS\n"); break;
            case 68: printf("\t\t\t\tFLUMINENSE\n"); break;
            case 69: printf("\t\t\t\tFUNCIONAR\n"); break;
            case 70: printf("\t\t\t\tFUNCIONÁRIO\n"); break;
            case 71: printf("\t\t\t\tFUNGO\n"); break;
            case 72: printf("\t\t\t\tGANCHO\n"); break;
            case 73: printf("\t\t\t\tGENTIL\n"); break;
            case 74: printf("\t\t\t\tGLICOSE\n"); break;
            case 75: printf("\t\t\t\tGLOBO\n"); break;
            case 76: printf("\t\t\t\tGOIABA\n"); break;
            case 77: printf("\t\t\t\tGOIABADA\n"); break;
            case 78: printf("\t\t\t\tGRAL\n"); break;
            case 79: printf("\t\t\t\tGRASNAR\n"); break;
            case 80: printf("\t\t\t\tGRISALHO\n"); break;
            case 81: printf("\t\t\t\tHORÁRIO\n"); break;
            case 82: printf("\t\t\t\tHUMORISTA\n"); break;
            case 83: printf("\t\t\t\tIGUANA\n"); break;
            case 84: printf("\t\t\t\tILUSTRAÇÃO\n"); break;
            case 85: printf("\t\t\t\tIMBECIL\n"); break;
            case 86: printf("\t\t\t\tINCOMODAR\n"); break;
            case 87: printf("\t\t\t\tINDEPENDÊNCIA\n"); break;
            case 88: printf("\t\t\t\tINDÚSTRIA\n"); break;
            case 89: printf("\t\t\t\tIRLANDA\n"); break;
            case 90: printf("\t\t\t\tISLÂNDIA\n"); break;
            case 91: printf("\t\t\t\tJACA\n"); break;
            case 92: printf("\t\t\t\tJARARACA\n"); break;
            case 93: printf("\t\t\t\tJIBÓIA\n"); break;
            case 94: printf("\t\t\t\tLACRAR\n"); break;
            case 95: printf("\t\t\t\tLAGARTO\n"); break;
            case 96: printf("\t\t\t\tLERDO\n"); break;
            case 97: printf("\t\t\t\tLONA\n"); break;
            case 98: printf("\t\t\t\tMADURO\n"); break;
            case 99: printf("\t\t\t\tMANIPULAR\n"); break;
            case 100: printf("\t\t\t\tMATILHA\n"); break;
            case 101: printf("\t\t\t\tMELÃO\n"); break;
            case 102: printf("\t\t\t\tMENSAGEM\n"); break;
            case 103: printf("\t\t\t\tMETROPOLITANO\n"); break;
            case 104: printf("\t\t\t\tMIADO\n"); break;
            case 105: printf("\t\t\t\tMONITOR\n"); break;
            case 106: printf("\t\t\t\tMONOMOTOR\n"); break;
            case 107: printf("\t\t\t\tMOSQUITO\n"); break;
            case 108: printf("\t\t\t\tMUÇULMANO\n"); break;
            case 109: printf("\t\t\t\tNÁUSEA\n"); break;
            case 110: printf("\t\t\t\tNEGOCIADOR\n"); break;
            case 111: printf("\t\t\t\tNORDESTE\n"); break;
            case 112: printf("\t\t\t\tNOROESTE\n"); break;
            case 113: printf("\t\t\t\tNOSTALGIA\n"); break;
            case 114: printf("\t\t\t\tORNITORRINCO\n"); break;
            case 115: printf("\t\t\t\tPALAVRA\n"); break;
            case 116: printf("\t\t\t\tPARABÓLICA\n"); break;
            case 117: printf("\t\t\t\tPARTO\n"); break;
            case 118: printf("\t\t\t\tPASTA\n"); break;
            case 119: printf("\t\t\t\tPEDIR\n"); break;
            case 120: printf("\t\t\t\tPÍTON\n"); break;
            case 121: printf("\t\t\t\tPLANILHA\n"); break;
            case 122: printf("\t\t\t\tPNEUMONIA\n"); break;
            case 123: printf("\t\t\t\tQUANTIDADE\n"); break;
            case 124: printf("\t\t\t\tQUEBRAR\n"); break;
            case 125: printf("\t\t\t\tQUEIMAR\n"); break;
            case 126: printf("\t\t\t\tQUINTAL\n"); break;
            case 127: printf("\t\t\t\tRECOMENDAÇÃO\n"); break;
            case 128: printf("\t\t\t\tRECADO\n"); break;
            case 129: printf("\t\t\t\tREFIL\n"); break;
            case 130: printf("\t\t\t\tRESIDÊNCIA\n"); break;
            case 131: printf("\t\t\t\tRINITE\n"); break;
            case 132: printf("\t\t\t\tROSCA\n"); break;
            case 133: printf("\t\t\t\tRUGIDO\n"); break;
            case 134: printf("\t\t\t\tSACRIFÍCIO\n"); break;
            case 135: printf("\t\t\t\tSAÚDE\n"); break;
            case 136: printf("\t\t\t\tSERINGA\n"); break;
            case 137: printf("\t\t\t\tSETOR\n"); break;
            case 138: printf("\t\t\t\tSIMULAÇÃO\n"); break;
            case 139: printf("\t\t\t\tSUBSTITUIR\n"); break;
            case 140: printf("\t\t\t\tSUCURI\n"); break;
            case 141: printf("\t\t\t\tSUPORTE\n"); break;
            case 142: printf("\t\t\t\tSUPREMO\n"); break;
            case 143: printf("\t\t\t\tTÉCNICO\n"); break;
            case 144: printf("\t\t\t\tTECNOLOGIA\n"); break;
            case 145: printf("\t\t\t\tTEQUILA\n"); break;
            case 146: printf("\t\t\t\tTERAPIA\n"); break;
            case 147: printf("\t\t\t\tTERRÍVEL\n"); break;
            case 148: printf("\t\t\t\tTESTÍCULO\n"); break;
            case 149: printf("\t\t\t\tTRINTA\n"); break;
            case 150: printf("\t\t\t\tUÍSQUE\n"); break;
            case 151: printf("\t\t\t\tURBANO\n"); break;
            case 152: printf("\t\t\t\tVIGÉSIMO\n"); break;
            case 153: printf("\t\t\t\tZODÍACO\n"); break;
            case 154: printf("\t\t\t\tZONA\n"); break;
            case 155: printf("\t\t\t\tNÓRDICO\n"); break;
            case 156: printf("\t\t\t\tSABRE\n"); break;
            case 157: printf("\t\t\t\tSUICÍDIO\n"); break;
            case 158: printf("\t\t\t\tTORTURA\n"); break;
            case 159: printf("\t\t\t\tSEMELHANTE\n"); break;
            case 160: printf("\t\t\t\tPENTEADO\n"); break;
            case 161: printf("\t\t\t\tJURÁSSICO\n"); break;
            case 162: printf("\t\t\t\tDESCREVER\n"); break;
            case 163: printf("\t\t\t\tLATARIA\n"); break;
            case 164: printf("\t\t\t\tPERIQUITO\n"); break;
            case 165: printf("\t\t\t\tENGOLIR\n"); break;
            case 166: printf("\t\t\t\tBÁSICO\n"); break;
            case 167: printf("\t\t\t\tALCALINA\n"); break;
            case 168: printf("\t\t\t\tFARPA\n"); break;
            case 169: printf("\t\t\t\tREVANCHE\n"); break;
            case 170: printf("\t\t\t\tDÓ\n"); break;
            case 171: printf("\t\t\t\tARCO-ÍRIS\n"); break;
            case 172: printf("\t\t\t\tDERROTADO\n"); break;
            case 173: printf("\t\t\t\tDESISTIR\n"); break;
            case 174: printf("\t\t\t\tCIANO\n"); break;
            case 175: printf("\t\t\t\tBAURU\n"); break;
            case 176: printf("\t\t\t\tMAMONA\n"); break;
            case 177: printf("\t\t\t\tTROMBONE\n"); break;
            case 178: printf("\t\t\t\tHAVAIANAS\n"); break;
            case 179: printf("\t\t\t\tESSÊNCIA\n"); break;
            case 180: printf("\t\t\t\tPERPENDICULAR\n"); break;
            case 181: printf("\t\t\t\tGERAÇÃO\n"); break;
            case 182: printf("\t\t\t\tMINGUANTE\n"); break;
            case 183: printf("\t\t\t\tCARISMA\n"); break;
            case 184: printf("\t\t\t\tSINOPSE\n"); break;
            case 185: printf("\t\t\t\tFOGUETE\n"); break;
            case 186: printf("\t\t\t\tBAZUCA\n"); break;
            case 187: printf("\t\t\t\tTORPEDO\n"); break;
            case 188: printf("\t\t\t\tCASTANHO\n"); break;
            case 189: printf("\t\t\t\tFIEL\n"); break;
            case 190: printf("\t\t\t\tFANTASIA\n"); break;
            case 191: printf("\t\t\t\tTOPETE\n"); break;
            case 192: printf("\t\t\t\tFRANJA\n"); break;
            case 193: printf("\t\t\t\tCACHO\n"); break;
            case 194: printf("\t\t\t\tSEGUIR\n"); break;
            case 195: printf("\t\t\t\tENROLADO\n"); break;
            case 196: printf("\t\t\t\tCICLO\n"); break;
            case 197: printf("\t\t\t\tSILO\n"); break;
            case 198: printf("\t\t\t\tCAPTURAR\n"); break;
            case 199: printf("\t\t\t\tVISITA\n"); break;
            case 200: printf("\t\t\t\tDESAFIO\n"); break;
            case 201: printf("\t\t\t\tLANÇAMENTO\n"); break;
            case 202: printf("\t\t\t\tTOM\n"); break;
            case 203: printf("\t\t\t\tINCRÍVEL\n"); break;
            case 204: printf("\t\t\t\tOFENDER\n"); break;
            case 205: printf("\t\t\t\tXINGAMENTO\n"); break;
            case 206: printf("\t\t\t\tASSUNTO\n"); break;
            case 207: printf("\t\t\t\tTERRÁQUIO\n"); break;
            case 208: printf("\t\t\t\tULTRA\n"); break;
            case 209: printf("\t\t\t\tPSÍQUICO\n"); break;
            case 210: printf("\t\t\t\tBALIZA\n"); break;
            case 211: printf("\t\t\t\tEPISÓDIO\n"); break;
            case 212: printf("\t\t\t\tDUBLADOR\n"); break;
            case 213: printf("\t\t\t\tFERVER\n"); break;
            case 214: printf("\t\t\t\tEBULIÇÃO\n"); break;
            case 215: printf("\t\t\t\tCHALÉ\n"); break;
            case 216: printf("\t\t\t\tPÔSTER\n"); break;
            case 217: printf("\t\t\t\tCOLECIONAR\n"); break;
            case 218: printf("\t\t\t\tBRAILE\n"); break;
            case 219: printf("\t\t\t\tHIATO\n"); break;
            case 220: printf("\t\t\t\tPIRRALHO\n"); break;
            case 221: printf("\t\t\t\tIRRITAR\n"); break;
            case 222: printf("\t\t\t\tENGARRAFAMENTO\n"); break;
            case 223: printf("\t\t\t\tENGAVETAMENTO\n"); break;
            case 224: printf("\t\t\t\tREAÇÃO\n"); break;
            case 225: printf("\t\t\t\tPLUMA\n"); break;
            case 226: printf("\t\t\t\tFOLGADO\n"); break;
            case 227: printf("\t\t\t\tESTIMAÇÃO\n"); break;
            case 228: printf("\t\t\t\tDOMESTICAR\n"); break;
            case 229: printf("\t\t\t\tDOMADOR\n"); break;
            case 230: printf("\t\t\t\tATUAL\n"); break;
            case 231: printf("\t\t\t\tINOVAR\n"); break;
            case 232: printf("\t\t\t\tCAMALEÃO\n"); break;
            case 233: printf("\t\t\t\tTRILHA\n"); break;
            case 234: printf("\t\t\t\tFÃ\n"); break;
            case 235: printf("\t\t\t\tÍDOLO\n"); break;
            case 236: printf("\t\t\t\tCÁLCULO\n"); break;
            case 237: printf("\t\t\t\tESPÍRITO\n"); break;
            case 238: printf("\t\t\t\tHEPTALHÃO\n"); break;
            case 239: printf("\t\t\t\tHEXALHÃO\n"); break;
            case 240: printf("\t\t\t\tPUXA-SACO\n"); break;
            case 241: printf("\t\t\t\tEVENTO\n"); break;
            case 242: printf("\t\t\t\tOBELISCO\n"); break;
            case 243: printf("\t\t\t\tANELAR\n"); break;
            case 244: printf("\t\t\t\tTRIO\n"); break;
            case 245: printf("\t\t\t\tREGRA\n"); break;
            case 246: printf("\t\t\t\tQUARTETO\n"); break;
            case 247: printf("\t\t\t\tQUINTETO\n"); break;
            case 248: printf("\t\t\t\tPECADO\n"); break;
            case 249: printf("\t\t\t\tCOMA\n"); break;
            case 250: printf("\t\t\t\tENXAQUECA\n"); break;
            case 251: printf("\t\t\t\tABÓBORA\n"); break;
            case 252: printf("\t\t\t\tABRAÇO\n"); break;
            case 253: printf("\t\t\t\tAÇÃO\n"); break;
            case 254: printf("\t\t\t\tAÇO\n"); break;
            case 255: printf("\t\t\t\tADEGA\n"); break;
            case 256: printf("\t\t\t\tADEUS\n"); break;
            case 257: printf("\t\t\t\tADULTO\n"); break;
            case 258: printf("\t\t\t\tADVERSÁRIO\n"); break;
            case 259: printf("\t\t\t\tADVOGADO\n"); break;
            case 260: printf("\t\t\t\tAEROMOÇA\n"); break;
            case 261: printf("\t\t\t\tAGÊNCIA\n"); break;
            case 262: printf("\t\t\t\tAGITADO\n"); break;
            case 263: printf("\t\t\t\tÁGUIA\n"); break;
            case 264: printf("\t\t\t\tAGULHA\n"); break;
            case 265: printf("\t\t\t\tAINDA\n"); break;
            case 266: printf("\t\t\t\tALDEIA\n"); break;
            case 267: printf("\t\t\t\tALFACE\n"); break;
            case 268: printf("\t\t\t\tALGEMA\n"); break;
            case 269: printf("\t\t\t\tALGODÃO\n"); break;
            case 270: printf("\t\t\t\tALIANÇA\n"); break;
            case 271: printf("\t\t\t\tALICATE\n"); break;
            case 272: printf("\t\t\t\tALHO\n"); break;
            case 273: printf("\t\t\t\tALMA\n"); break;
            case 274: printf("\t\t\t\tALMOFADA\n"); break;
            case 275: printf("\t\t\t\tALTAR\n"); break;
            case 276: printf("\t\t\t\tAMARGO\n"); break;
            case 277: printf("\t\t\t\tAMBULÂNCIA\n"); break;
            case 278: printf("\t\t\t\tAMÉRICA\n"); break;
            case 279: printf("\t\t\t\tAMIZADE\n"); break;
            case 280: printf("\t\t\t\tANÃO\n"); break;
            case 281: printf("\t\t\t\tANDAR\n"); break;
            case 282: printf("\t\t\t\tANJO\n"); break;
            case 283: printf("\t\t\t\tANTENA\n"); break;
            case 284: printf("\t\t\t\tANTIGO\n"); break;
            case 285: printf("\t\t\t\tAPAIXONADO\n"); break;
            case 286: printf("\t\t\t\tAPARTAMENTO\n"); break;
            case 287: printf("\t\t\t\tAPERITIVO\n"); break;
            case 288: printf("\t\t\t\tAPERTADO\n"); break;
            case 289: printf("\t\t\t\tAPLAUSO\n"); break;
            case 290: printf("\t\t\t\tAPOSENTADO\n"); break;
            case 291: printf("\t\t\t\tAPOSTA\n"); break;
            case 292: printf("\t\t\t\tAQUÁRIO\n"); break;
            case 293: printf("\t\t\t\tAR\n"); break;
            case 294: printf("\t\t\t\tARAME\n"); break;
            case 295: printf("\t\t\t\tARMA\n"); break;
            case 296: printf("\t\t\t\tARMADILHA\n"); break;
            case 297: printf("\t\t\t\tAROMA\n"); break;
            case 298: printf("\t\t\t\tASFALTO\n"); break;
            case 299: printf("\t\t\t\tASSASSINATO\n"); break;
            case 300: printf("\t\t\t\tATOR\n"); break;
            case 301: printf("\t\t\t\tATRIZ\n"); break;
            case 302: printf("\t\t\t\tAUDITÓRIO\n"); break;
            case 303: printf("\t\t\t\tAUSTRÁLIA\n"); break;
            case 304: printf("\t\t\t\tAUTÓGRAFO\n"); break;
            case 305: printf("\t\t\t\tAVENTAL\n"); break;
            case 306: printf("\t\t\t\tAVESTRUZ\n"); break;
            case 307: printf("\t\t\t\tAVIÃO\n"); break;
            case 308: printf("\t\t\t\tAZEITE\n"); break;
            case 309: printf("\t\t\t\tAZEITONA\n"); break;
            case 310: printf("\t\t\t\tCABIDE\n"); break;
            case 311: printf("\t\t\t\tCABINE\n"); break;
            case 312: printf("\t\t\t\tCABO\n"); break;
            case 313: printf("\t\t\t\tCABRA\n"); break;
            case 314: printf("\t\t\t\tCAÇADOR\n"); break;
            case 315: printf("\t\t\t\tCAÇULA\n"); break;
            case 316: printf("\t\t\t\tCADEADO\n"); break;
            case 317: printf("\t\t\t\tCADEIA\n"); break;
            case 318: printf("\t\t\t\tCAFÉ\n"); break;
            case 319: printf("\t\t\t\tCAIPIRA\n"); break;
            case 320: printf("\t\t\t\tCAIXA\n"); break;
            case 321: printf("\t\t\t\tCALÇADA\n"); break;
            case 322: printf("\t\t\t\tCALCULADORA\n"); break;
            case 323: printf("\t\t\t\tCALENDÁRIO\n"); break;
            case 324: printf("\t\t\t\tCAMARÃO\n"); break;
            case 325: printf("\t\t\t\tCAMPO\n"); break;
            case 326: printf("\t\t\t\tCANGURU\n"); break;
            case 327: printf("\t\t\t\tCANHÃO\n"); break;
            case 328: printf("\t\t\t\tCANIL\n"); break;
            case 329: printf("\t\t\t\tCANIVETE\n"); break;
            case 330: printf("\t\t\t\tCANTINA\n"); break;
            case 331: printf("\t\t\t\tCAPELA\n"); break;
            case 332: printf("\t\t\t\tCAPIVARA\n"); break;
            case 333: printf("\t\t\t\tCARACOL\n"); break;
            case 334: printf("\t\t\t\tCARINHO\n"); break;
            case 335: printf("\t\t\t\tCARNAVAL\n"); break;
            case 336: printf("\t\t\t\tBÚSSOLA\n"); break;
            case 337: printf("\t\t\t\tCARTEIRA\n"); break;
            case 338: printf("\t\t\t\tCARTEIRO\n"); break;
            case 339: printf("\t\t\t\tCARVÃO\n"); break;
            case 340: printf("\t\t\t\tCASA\n"); break;
            case 341: printf("\t\t\t\tCASACO\n"); break;
            case 342: printf("\t\t\t\tCASTANHA\n"); break;
            case 343: printf("\t\t\t\tCASTELO\n"); break;
            case 344: printf("\t\t\t\tCAVALHEIRO\n"); break;
            case 345: printf("\t\t\t\tCAVERNA\n"); break;
            case 346: printf("\t\t\t\tTINTA\n"); break;
            case 347: printf("\t\t\t\tTÍTULO\n"); break;
            case 348: printf("\t\t\t\tCEGONHA\n"); break;
            case 349: printf("\t\t\t\tCELA\n"); break;
            case 350: printf("\t\t\t\tCELEBRIDADE\n"); break;
            case 351: printf("\t\t\t\tDÁLMATA\n"); break;
            case 352: printf("\t\t\t\tDANÇA\n"); break;
            case 353: printf("\t\t\t\tDÉCADA\n"); break;
            case 354: printf("\t\t\t\tDENTADURA\n"); break;
            case 355: printf("\t\t\t\tDENTE\n"); break;
            case 356: printf("\t\t\t\tDESENHO\n"); break;
            case 357: printf("\t\t\t\tDESERTO\n"); break;
            case 358: printf("\t\t\t\tDESODORANTE\n"); break;
            case 359: printf("\t\t\t\tDIAGONAL\n"); break;
            case 360: printf("\t\t\t\tDIAMANTE\n"); break;
            case 361: printf("\t\t\t\tDINAMITE\n"); break;
            case 362: printf("\t\t\t\tDINOSSAURO\n"); break;
            case 363: printf("\t\t\t\tDIRETOR\n"); break;
            case 364: printf("\t\t\t\tDISCO\n"); break;
            case 365: printf("\t\t\t\tDITADURA\n"); break;
            case 366: printf("\t\t\t\tDIVERSÃO\n"); break;
            case 367: printf("\t\t\t\tDOM\n"); break;
            case 368: printf("\t\t\t\tDOMINÓ\n"); break;
            case 369: printf("\t\t\t\tDONO\n"); break;
            case 370: printf("\t\t\t\tELEGANTE\n"); break;
            case 371: printf("\t\t\t\tELEIÇÃO\n"); break;
            case 372: printf("\t\t\t\tELEMENTO\n"); break;
            case 373: printf("\t\t\t\tELEVADOR\n"); break;
            case 374: printf("\t\t\t\tELITE\n"); break;
            case 375: printf("\t\t\t\tELMO\n"); break;
            case 376: printf("\t\t\t\tEMPATAR\n"); break;
            case 377: printf("\t\t\t\tEMPOLGAÇÃO\n"); break;
            case 378: printf("\t\t\t\tEMPREGADO\n"); break;
            case 379: printf("\t\t\t\tEMPRESÁRIO\n"); break;
            case 380: printf("\t\t\t\tEMPRESTAR\n"); break;
            case 381: printf("\t\t\t\tENCHENTE\n"); break;
            case 382: printf("\t\t\t\tENFERMEIRA\n"); break;
            case 383: printf("\t\t\t\tENTREVISTA\n"); break;
            case 384: printf("\t\t\t\tENVELOPE\n"); break;
            case 385: printf("\t\t\t\tENXADA\n"); break;
            case 386: printf("\t\t\t\tEQUIPE\n"); break;
            case 387: printf("\t\t\t\tESCANTEIO\n"); break;
            case 388: printf("\t\t\t\tESCONDIDO\n"); break;
            case 389: printf("\t\t\t\tESCORPIÃO\n"); break;
            case 390: printf("\t\t\t\tESCRAVIDÃO\n"); break;
            case 391: printf("\t\t\t\tESGOTO\n"); break;
            case 392: printf("\t\t\t\tESGRIMA\n"); break;
            case 393: printf("\t\t\t\tESMALTE\n"); break;
            case 394: printf("\t\t\t\tESMERALDA\n"); break;
            case 395: printf("\t\t\t\tESMOLA\n"); break;
            case 396: printf("\t\t\t\tESPAÇO\n"); break;
            case 397: printf("\t\t\t\tESPAGUETE\n"); break;
            case 398: printf("\t\t\t\tESPANTALHO\n"); break;
            case 399: printf("\t\t\t\tESPECIAL\n"); break;
            case 400: printf("\t\t\t\tESPETO\n"); break;
            case 401: printf("\t\t\t\tESPIÃO\n"); break;
            case 402: printf("\t\t\t\tESPINAFRE\n"); break;
            case 403: printf("\t\t\t\tESPINGARDA\n"); break;
            case 404: printf("\t\t\t\tESQUIAR\n"); break;
            case 405: printf("\t\t\t\tESQUILO\n"); break;
            case 406: printf("\t\t\t\tESTACA\n"); break;
            case 407: printf("\t\t\t\tESTRANHO\n"); break;
            case 408: printf("\t\t\t\tESTUDANTE\n"); break;
            case 409: printf("\t\t\t\tESTUDO\n"); break;
            case 410: printf("\t\t\t\tESTRADA\n"); break;
            case 411: printf("\t\t\t\tEXCELÊNCIA\n"); break;
            case 412: printf("\t\t\t\tEXCURSÃO\n"); break;
            case    413:    printf("\t\t\t\tEXÉRCITO\n"); break;
            case    414:    printf("\t\t\t\tEXPLOSÃO\n"); break;
            case    415:    printf("\t\t\t\tEXTENSÃO\n"); break;
            case	416	:	printf("\t\t\t	GOLFE	\n"); break;
            case	417	:	printf("\t\t\t	GOLFINHO	\n"); break;
            case	418	:	printf("\t\t\t	GOLPE	\n"); break;
            case	419	:	printf("\t\t\t	GORDURA	\n"); break;
            case	420	:	printf("\t\t\t	GRÁFICO	\n"); break;
            case	421	:	printf("\t\t\t	GRÁTIS	\n"); break;
            case	422	:	printf("\t\t\t	GRAVATA	\n"); break;
            case	423	:	printf("\t\t\t	GRUPO	\n"); break;
            case	424	:	printf("\t\t\t	GUARDA	\n"); break;
            case	425	:	printf("\t\t\t	GUARDANAPO	\n"); break;
            case	426	:	printf("\t\t\t	GUITARRA	\n"); break;
            case	427	:	printf("\t\t\t	HÁLITO	\n"); break;
            case	428	:	printf("\t\t\t	HARPA	\n"); break;
            case	429	:	printf("\t\t\t	HÉLICE	\n"); break;
            case	430	:	printf("\t\t\t	HELICÓPTERO	\n"); break;
            case	431	:	printf("\t\t\t	HORA	\n"); break;
            case	432	:	printf("\t\t\t	HORÓSCOPO	\n"); break;
            case	433	:	printf("\t\t\t	HOTEL	\n"); break;
            case	434	:	printf("\t\t\t	HUMOR	\n"); break;
            case	435	:	printf("\t\t\t	VIDENTE	\n"); break;
            case	436	:	printf("\t\t\t	VIOLINO	\n"); break;
            case	437	:	printf("\t\t\t	VIZINHO	\n"); break;
            case	438	:	printf("\t\t\t	VOLANTE	\n"); break;
            case	439	:	printf("\t\t\t	VOLUNTÁRIO	\n"); break;
            case	440	:	printf("\t\t\t	VULCÃO	\n"); break;
            case	441	:	printf("\t\t\t	IATE	\n"); break;
            case	442	:	printf("\t\t\t	IDADE	\n"); break;
            case	443	:	printf("\t\t\t	IDEIA	\n"); break;
            case	444	:	printf("\t\t\t	IGLU	\n"); break;
            case	445	:	printf("\t\t\t	ILHA	\n"); break;
            case	446	:	printf("\t\t\t	ILUSÃO	\n"); break;
            case	447	:	printf("\t\t\t	IMÓVEL	\n"); break;
            case	448	:	printf("\t\t\t	IMPÉRIO	\n"); break;
            case	449	:	printf("\t\t\t	IMPRESSORA	\n"); break;
            case	450	:	printf("\t\t\t	ÍNDIO	\n"); break;
            case	451	:	printf("\t\t\t	INFORMÁTICA	\n"); break;
            case	452	:	printf("\t\t\t	INSÔNIA	\n"); break;
            case	453	:	printf("\t\t\t	INTERVALO	\n"); break;
            case	454	:	printf("\t\t\t	INUNDAÇÃO	\n"); break;
            case	455	:	printf("\t\t\t	IRRACIONAL	\n"); break;
            case	456	:	printf("\t\t\t	ISCA	\n"); break;
            case	457	:	printf("\t\t\t	ISOPOR	\n"); break;
            case	458	:	printf("\t\t\t	ISQUEIRO	\n"); break;
            case	459	:	printf("\t\t\t	MOINHO	\n"); break;
            case	460	:	printf("\t\t\t	MOLHO	\n"); break;
            case	461	:	printf("\t\t\t	TRENÓ	\n"); break;
            case	462	:	printf("\t\t\t	MONARQUIA	\n"); break;
            case	463	:	printf("\t\t\t	MONGE	\n"); break;
            case	464	:	printf("\t\t\t	TRANSPORTE	\n"); break;
            case	465	:	printf("\t\t\t	MONTANHA	\n"); break;
            case	466	:	printf("\t\t\t	MORDOMO	\n"); break;
            case	467	:	printf("\t\t\t	MOSCA	\n"); break;
            case	468	:	printf("\t\t\t	MOVIMENTO	\n"); break;
            case	469	:	printf("\t\t\t	MÚMIA	\n"); break;
            case	470	:	printf("\t\t\t	MUNICÍPIO	\n"); break;
            case	471	:	printf("\t\t\t	MÚSCULO	\n"); break;
            case	472	:	printf("\t\t\t	MUSEU	\n"); break;
            case	473	:	printf("\t\t\t	TRILHO	\n"); break;
            case	474	:	printf("\t\t\t	TURBANTE	\n"); break;
            case	475	:	printf("\t\t\t	MUTANTE	\n"); break;
            case	476	:	printf("\t\t\t	JARDIM	\n"); break;
            case	477	:	printf("\t\t\t	JARRA	\n"); break;
            case	478	:	printf("\t\t\t	JOGAR	\n"); break;
            case	479	:	printf("\t\t\t	JOGO	\n"); break;
            case	480	:	printf("\t\t\t	JORNALISMO	\n"); break;
            case	481	:	printf("\t\t\t	JULGAMENTO	\n"); break;
            case	482	:	printf("\t\t\t	JUMENTO	\n"); break;
            case	483	:	printf("\t\t\t	TEXTO	\n"); break;
            case	484	:	printf("\t\t\t	POLÍTICO	\n"); break;
            case	485	:	printf("\t\t\t	POLUIR	\n"); break;
            case	486	:	printf("\t\t\t	PÓLVORA	\n"); break;
            case	487	:	printf("\t\t\t	PONTUAL	\n"); break;
            case	488	:	printf("\t\t\t	POPULAR	\n"); break;
            case	489	:	printf("\t\t\t	PORÃO	\n"); break;
            case	490	:	printf("\t\t\t	POSSÍVEL	\n"); break;
            case	491	:	printf("\t\t\t	POSTE	\n"); break;
            case	492	:	printf("\t\t\t	PRANCHA	\n"); break;
            case	493	:	printf("\t\t\t	CENTOPÉIA	\n"); break;
            case	494	:	printf("\t\t\t	CERA	\n"); break;
            case	495	:	printf("\t\t\t	CESTA	\n"); break;
            case	496	:	printf("\t\t\t	CHÁ	\n"); break;
            case	497	:	printf("\t\t\t	CHALEIRA	\n"); break;
            case	498	:	printf("\t\t\t	CHAMPANHE	\n"); break;
            case	499	:	printf("\t\t\t	CHEIRO	\n"); break;
            case	500	:	printf("\t\t\t	CHEQUE	\n"); break;
            case	501	:	printf("\t\t\t	CHICOTE	\n"); break;
            case	502	:	printf("\t\t\t	CHIMPANZÉ	\n"); break;
            case	503	:	printf("\t\t\t	CHINELO	\n"); break;
            case	504	:	printf("\t\t\t	CIENTISTA	\n"); break;
            case	505	:	printf("\t\t\t	CIGANO	\n"); break;
            case	506	:	printf("\t\t\t	CINEASTA	\n"); break;
            case	507	:	printf("\t\t\t	CINEMA	\n"); break;
            case	508	:	printf("\t\t\t	CIÚME	\n"); break;
            case	509	:	printf("\t\t\t	CINZEIRO	\n"); break;
            case	510	:	printf("\t\t\t	CIPÓ	\n"); break;
            case	511	:	printf("\t\t\t	CLÁSSICO	\n"); break;
            case	512	:	printf("\t\t\t	COBERTOR	\n"); break;
            case	513	:	printf("\t\t\t	CÓCEGAS	\n"); break;
            case	514	:	printf("\t\t\t	CÓDIGO	\n"); break;
            case	515	:	printf("\t\t\t	COGUMELO	\n"); break;
            case	516	:	printf("\t\t\t	COLCHÃO	\n"); break;
            case	517	:	printf("\t\t\t	COMANDO	\n"); break;
            case	518	:	printf("\t\t\t	LAÇO	\n"); break;
            case	519	:	printf("\t\t\t	LADO	\n"); break;
            case	520	:	printf("\t\t\t	LÂMPADA	\n"); break;
            case	521	:	printf("\t\t\t	LASANHA	\n"); break;
            case	522	:	printf("\t\t\t	LATERAL	\n"); break;
            case	523	:	printf("\t\t\t	LEI	\n"); break;
            case	524	:	printf("\t\t\t	ZAGUEIRO	\n"); break;
            case	525	:	printf("\t\t\t	ZANGADO	\n"); break;
            case	526	:	printf("\t\t\t	ZOOLÓGICO	\n"); break;
            case	527	:	printf("\t\t\t	LENDA	\n"); break;
            case	528	:	printf("\t\t\t	LETRA	\n"); break;
            case	529	:	printf("\t\t\t	LINGUIÇA	\n"); break;
            case	530	:	printf("\t\t\t	LIQUIDIFICADOR	\n"); break;
            case	531	:	printf("\t\t\t	LOCOMOTIVA	\n"); break;
            case	532	:	printf("\t\t\t	TENTÁCULO	\n"); break;
            case	533	:	printf("\t\t\t	TEOREMA	\n"); break;
            case	534	:	printf("\t\t\t	LOTERIA	\n"); break;
            case	535	:	printf("\t\t\t	LOUÇA	\n"); break;
            case	536	:	printf("\t\t\t	LUPA	\n"); break;
            case	537	:	printf("\t\t\t	LUXO	\n"); break;
            case	538	:	printf("\t\t\t	MAÇANETA	\n"); break;
            case	539	:	printf("\t\t\t	MADEIRA	\n"); break;
            case	540	:	printf("\t\t\t	MAIÔ	\n"); break;
            case	541	:	printf("\t\t\t	MALA	\n"); break;
            case	542	:	printf("\t\t\t	MÁFIA	\n"); break;
            case	543	:	printf("\t\t\t	MAGIA	\n"); break;
            case	544	:	printf("\t\t\t	MÁGICO	\n"); break;
            case	545	:	printf("\t\t\t	MANDIOCA	\n"); break;
            case	546	:	printf("\t\t\t	MANEQUIM	\n"); break;
            case	547	:	printf("\t\t\t	MANGA	\n"); break;
            case	548	:	printf("\t\t\t	VERGONHA	\n"); break;
            case	549	:	printf("\t\t\t	VERNIZ	\n"); break;
            case	550	:	printf("\t\t\t	VIAGEM	\n"); break;
            case	551	:	printf("\t\t\t	MANICURE	\n"); break;
            case	552	:	printf("\t\t\t	MANIFESTAÇÃO	\n"); break;
            case	553	:	printf("\t\t\t	MARCADOR	\n"); break;
            case	554	:	printf("\t\t\t	MARFIM	\n"); break;
            case	555	:	printf("\t\t\t	MARGARIDA	\n"); break;
            case	556	:	printf("\t\t\t	MARROM	\n"); break;
            case	557	:	printf("\t\t\t	MÁSCARA	\n"); break;
            case	558	:	printf("\t\t\t	MASSAGEM	\n"); break;
            case	559	:	printf("\t\t\t	MEGAFONE	\n"); break;
            case	560	:	printf("\t\t\t	MEMÓRIA	\n"); break;
            case	561	:	printf("\t\t\t	MENDIGO	\n"); break;
            case	562	:	printf("\t\t\t	MENTAL	\n"); break;
            case	563	:	printf("\t\t\t	MERCADO	\n"); break;
            case	564	:	printf("\t\t\t	MERCÚRIO	\n"); break;
            case	565	:	printf("\t\t\t	METAL	\n"); break;
            case	566	:	printf("\t\t\t	MESTRE	\n"); break;
            case	567	:	printf("\t\t\t	MICROFONE	\n"); break;
            case	568	:	printf("\t\t\t	NATAÇÃO	\n"); break;
            case	569	:	printf("\t\t\t	NÁUFRAGO	\n"); break;
            case	570	:	printf("\t\t\t	NAVALHA	\n"); break;
            case	571	:	printf("\t\t\t	NAVE	\n"); break;
            case	572	:	printf("\t\t\t	NEVE	\n"); break;
            case	573	:	printf("\t\t\t	NINHO	\n"); break;
            case	574	:	printf("\t\t\t	NINJA	\n"); break;
            case	575	:	printf("\t\t\t	NÓ	\n"); break;
            case	576	:	printf("\t\t\t	NOIVA	\n"); break;
            case	577	:	printf("\t\t\t  NOME	\n"); break;
            case	578	:	printf("\t\t\t	NONSA	\n"); break;
            case	579	:	printf("\t\t\t	NOVELA	\n"); break;
            case	580	:	printf("\t\t\t	NOVIDADE	\n"); break;
            case	581	:	printf("\t\t\t	PRAZER	\n"); break;
            case	582	:	printf("\t\t\t	PREFERIDO	\n"); break;
            case	583	:	printf("\t\t\t	PREGUIÇOSO	\n"); break;
            case	584	:	printf("\t\t\t	PREVISÃO	\n"); break;
            case	585	:	printf("\t\t\t	TRIPÉ	\n"); break;
            case	586	:	printf("\t\t\t	PRISIONEIRO	\n"); break;
            case	587	:	printf("\t\t\t	PROFUNDO	\n"); break;
            case	588	:	printf("\t\t\t	TROCO	\n"); break;
            case	589	:	printf("\t\t\t	TROFÉU	\n"); break;
            case	590	:	printf("\t\t\t	TRONO	\n"); break;
            case	591	:	printf("\t\t\t	PROMESSA	\n"); break;
            case	592	:	printf("\t\t\t	PROTEÇÃO	\n"); break;
            case	593	:	printf("\t\t\t	PSICÓLOGO	\n"); break;
            case	594	:	printf("\t\t\t	PUDIM	\n"); break;
            case	595	:	printf("\t\t\t	PULMÃO	\n"); break;
            case	596	:	printf("\t\t\t	PULSO	\n"); break;
            case	597	:	printf("\t\t\t	OBRIGADO	\n"); break;
            case	598	:	printf("\t\t\t	OCUPADO	\n"); break;
            case	599	:	printf("\t\t\t	OFICINA	\n"); break;
            case	600	:	printf("\t\t\t	ÓRBITA	\n"); break;
            case	601	:	printf("\t\t\t	ORQUESTRA	\n"); break;
            case	602	:	printf("\t\t\t	OUTRO	\n"); break;
            case	603	:	printf("\t\t\t	OVELHA	\n"); break;
            case	604	:	printf("\t\t\t	XADREZ	\n"); break;
            case	605	:	printf("\t\t\t	XAROPE	\n"); break;
            case	606	:	printf("\t\t\t	XÍCARA	\n"); break;
            case	607	:	printf("\t\t\t	COMETA	\n"); break;
            case	608	:	printf("\t\t\t	COMPARTILHAR	\n"); break;
            case	609	:	printf("\t\t\t	COMPLETO	\n"); break;
            case	610	:	printf("\t\t\t	COMPRIMIDO	\n"); break;
            case	611	:	printf("\t\t\t	COMPUTADOR	\n"); break;
            case	612	:	printf("\t\t\t	CONCHA	\n"); break;
            case	613	:	printf("\t\t\t	CONCORRÊNCIA	\n"); break;
            case	614	:	printf("\t\t\t	CONDE	\n"); break;
            case	615	:	printf("\t\t\t	CONHECIDO	\n"); break;
            case	616	:	printf("\t\t\t	CONTINENTE	\n"); break;
            case	617	:	printf("\t\t\t	CONVITE	\n"); break;
            case	618	:	printf("\t\t\t	CORDA	\n"); break;
            case	619	:	printf("\t\t\t	CORDIAL	\n"); break;
            case	620	:	printf("\t\t\t	CORNETA	\n"); break;
            case	621	:	printf("\t\t\t	CORO	\n"); break;
            case	622	:	printf("\t\t\t	CORRIDA	\n"); break;
            case	623	:	printf("\t\t\t	CORTE	\n"); break;
            case	624	:	printf("\t\t\t	COSTELA	\n"); break;
            case	625	:	printf("\t\t\t	COZINHAR	\n"); break;
            case	626	:	printf("\t\t\t	CRIADOR	\n"); break;
            case	627	:	printf("\t\t\t	CRIME	\n"); break;
            case	628	:	printf("\t\t\t	CRUZEIRO	\n"); break;
            case	629	:	printf("\t\t\t	CUECA	\n"); break;
            case	630	:	printf("\t\t\t	CUIDADO	\n"); break;
            case	631	:	printf("\t\t\t	PADRE	\n"); break;
            case	632	:	printf("\t\t\t	PÁGINA	\n"); break;
            case	633	:	printf("\t\t\t	PAISAGEM	\n"); break;
            case	634	:	printf("\t\t\t	PALÁCIO	\n"); break;
            case	635	:	printf("\t\t\t	PALETÓ	\n"); break;
            case	636	:	printf("\t\t\t	PALITO	\n"); break;
            case	637	:	printf("\t\t\t	PANDA	\n"); break;
            case	638	:	printf("\t\t\t	PANDEIRO	\n"); break;
            case	639	:	printf("\t\t\t	PÂNTANO	\n"); break;
            case	640	:	printf("\t\t\t	PÃO	\n"); break;
            case	641	:	printf("\t\t\t	PARAFUSO	\n"); break;
            case	642	:	printf("\t\t\t	PARAÍSO	\n"); break;
            case	643	:	printf("\t\t\t	PARALELO	\n"); break;
            case	644	:	printf("\t\t\t	PAREDE	\n"); break;
            case	645	:	printf("\t\t\t	PARTIDO	\n"); break;
            case	646	:	printf("\t\t\t	PASSE	\n"); break;
            case	647	:	printf("\t\t\t	PASSEIO	\n"); break;
            case	648	:	printf("\t\t\t	PATERNO	\n"); break;
            case	649	:	printf("\t\t\t	PATINS	\n"); break;
            case	650	:	printf("\t\t\t	PAVÃO	\n"); break;
            case	651	:	printf("\t\t\t	PEDÁGIO	\n"); break;
            case	652	:	printf("\t\t\t	PELUDO	\n"); break;
            case	653	:	printf("\t\t\t	PERFIL	\n"); break;
            case	654	:	printf("\t\t\t	PESCOÇO	\n"); break;
            case	655	:	printf("\t\t\t	PÊSSEGO	\n"); break;
            case	656	:	printf("\t\t\t	PIADA	\n"); break;
            case	657	:	printf("\t\t\t	PIANO	\n"); break;
            case	658	:	printf("\t\t\t	PICO	\n"); break;
            case	659	:	printf("\t\t\t	PIEDADE	\n"); break;
            case	660	:	printf("\t\t\t	PIJAMA	\n"); break;
            case	661	:	printf("\t\t\t	PÍLULA	\n"); break;
            case	662	:	printf("\t\t\t	PIMENTA	\n"); break;
            case	663	:	printf("\t\t\t	PINGENTE	\n"); break;
            case	664	:	printf("\t\t\t	PINTOR	\n"); break;
            case	665	:	printf("\t\t\t	PIPA	\n"); break;
            case	666	:	printf("\t\t\t	PIRÂMIDE	\n"); break;
            case	667	:	printf("\t\t\t	PIRES	\n"); break;
            case	668	:	printf("\t\t\t	PIZZA	\n"); break;
            case	669	:	printf("\t\t\t	PLACA	\n"); break;
            case	670	:	printf("\t\t\t	PLÁSTICO	\n"); break;
            case	671	:	printf("\t\t\t	PÓDIO	\n"); break;
            case	672	:	printf("\t\t\t	POLEGAR	\n"); break;
            case	673	:	printf("\t\t\t	QUADRO	\n"); break;
            case	674	:	printf("\t\t\t	QUIETO	\n"); break;
            case	675	:	printf("\t\t\t	TÁBUA	\n"); break;
            case	676	:	printf("\t\t\t	TABULEIRO	\n"); break;
            case	677	:	printf("\t\t\t	TAPETE	\n"); break;
            case	678	:	printf("\t\t\t	TÁXI	\n"); break;
            case	679	:	printf("\t\t\t	UMBIGO	\n"); break;
            case	680	:	printf("\t\t\t	UNHA	\n"); break;
            case	681	:	printf("\t\t\t	UNIVERSIDADE	\n"); break;
            case	682	:	printf("\t\t\t	UNIVERSO	\n"); break;
            case	683	:	printf("\t\t\t	USINA	\n"); break;
            case	684	:	printf("\t\t\t	VACINA	\n"); break;
            case	685	:	printf("\t\t\t	VAPOR	\n"); break;
            case	686	:	printf("\t\t\t	VAREJO	\n"); break;
            case	687	:	printf("\t\t\t	VASSOURA	\n"); break;
            case	688	:	printf("\t\t\t	VAZAMENTO	\n"); break;
            case	689	:	printf("\t\t\t	VENTO	\n"); break;
            case	690	:	printf("\t\t\t	RADAR	\n"); break;
            case	691	:	printf("\t\t\t	RÁDIO	\n"); break;
            case	692	:	printf("\t\t\t	RAZÃO	\n"); break;
            case	693	:	printf("\t\t\t	REBOLAR	\n"); break;
            case	694	:	printf("\t\t\t	VERBO	\n"); break;
            case	695	:	printf("\t\t\t	RÉGUA	\n"); break;
            case	696	:	printf("\t\t\t	RELIGIÃO	\n"); break;
            case	697	:	printf("\t\t\t	RELÓGIO	\n"); break;
            case	698	:	printf("\t\t\t	REMÉDIO	\n"); break;
            case	699	:	printf("\t\t\t	REMO	\n"); break;
            case	700	:	printf("\t\t\t	REPÚBLICA	\n"); break;
            case	701	:	printf("\t\t\t	RESPONSÁVEL	\n"); break;
            case	702	:	printf("\t\t\t	REVISTA	\n"); break;
            case	703	:	printf("\t\t\t	RINOCERONTE	\n"); break;
            case	704	:	printf("\t\t\t	ROCHA	\n"); break;
            case	705	:	printf("\t\t\t	ROLETA	\n"); break;
            case	706	:	printf("\t\t\t	TELEVISÃO	\n"); break;
            case	707	:	printf("\t\t\t	TELESCÓPIO	\n"); break;
            case	708	:	printf("\t\t\t	TEMPESTADE	\n"); break;
            case	709	:	printf("\t\t\t	RURAL	\n"); break;
            case	710	:	printf("\t\t\t	SABOR	\n"); break;
            case	711	:	printf("\t\t\t	SALA	\n"); break;
            case	712	:	printf("\t\t\t	SALADA	\n"); break;
            case	713	:	printf("\t\t\t	SALIVA	\n"); break;
            case	714	:	printf("\t\t\t	SALTO	\n"); break;
            case	715	:	printf("\t\t\t	SAMBA	\n"); break;
            case	716	:	printf("\t\t\t	SANDUÍCHE	\n"); break;
            case	717	:	printf("\t\t\t	SAXOFONE	\n"); break;
            case	718	:	printf("\t\t\t	SEGREDO	\n"); break;
            case	719	:	printf("\t\t\t	SEGURANÇA	\n"); break;
            case	720	:	printf("\t\t\t	SELEÇÃO	\n"); break;
            case	721	:	printf("\t\t\t	SELO	\n"); break;
            case	722	:	printf("\t\t\t	SELVA	\n"); break;
            case	723	:	printf("\t\t\t	TECLADO	\n"); break;
            case	724	:	printf("\t\t\t	SEMINÁRIO	\n"); break;
            case	725	:	printf("\t\t\t	SENHA	\n"); break;
            case	726	:	printf("\t\t\t	SENHORA	\n"); break;
            case	727	:	printf("\t\t\t	SEQUÊNCIA	\n"); break;
            case	728	:	printf("\t\t\t	SÉRIE	\n"); break;
            case	729	:	printf("\t\t\t	SERTÃO	\n"); break;
            case	730	:	printf("\t\t\t	SINGULAR	\n"); break;
            case	731	:	printf("\t\t\t	SINO	\n"); break;
            case	732	:	printf("\t\t\t	SOBRANCELHA	\n"); break;
            case	733	:	printf("\t\t\t	SORRISO	\n"); break;
            case	734	:	printf("\t\t\t	SORTEIO	\n"); break;
            case	735	:	printf("\t\t\t	SUBMARINO	\n"); break;
            case	736	:	printf("\t\t\t	SUBSOLO	\n"); break;
            case	737	:	printf("\t\t\t	SUCO	\n"); break;
            case	738	:	printf("\t\t\t	SUNGA	\n"); break;
            case	739	:	printf("\t\t\t	SUOR	\n"); break;
            case	740	:	printf("\t\t\t	SUSPEITO	\n"); break;
        }
    }
    printf("\n\n\n\n");
    relogio(50);
    printf("\a");
    system("cls");
    mensagem();
}
void palavraDificil()
{
    int palavra;
    int i;
    system("color 4F");
    printf("\n\n\n\n");
    printf("\t\t\t   PALAVRAS DIFICEIS\n\n\n");
    for(i = 0; i < 6; i++)
    {
        palavra = rand() % 276;
        switch (palavra)
        {
            case 0: printf("\t\t\t\tACELGA\n"); break;
            case 1: printf("\t\t\t\tAGRIÃO\n"); break;
            case 2: printf("\t\t\t\tALGAZARRA\n"); break;
            case 3: printf("\t\t\t\tAMPOLA\n"); break;
            case 4: printf("\t\t\t\tAUTONOMIA\n"); break;
            case 5: printf("\t\t\t\tAUTÓPSIA\n"); break;
            case 6: printf("\t\t\t\tBALAÚSTRE\n"); break;
            case 7: printf("\t\t\t\tBARÔMETRO\n"); break;
            case 8: printf("\t\t\t\tBASÍLICA\n"); break;
            case 9: printf("\t\t\t\tBROA\n"); break;
            case 10: printf("\t\t\t\tCACHALOTE\n"); break;
            case 11: printf("\t\t\t\tCANDELABRO\n"); break;
            case 12: printf("\t\t\t\tCHULO\n"); break;
            case 13: printf("\t\t\t\tCONSPIRAÇÃO\n"); break;
            case 14: printf("\t\t\t\tCONSTITUIÇÃO\n"); break;
            case 15: printf("\t\t\t\tCREDOR\n"); break;
            case 16: printf("\t\t\t\tCRONOGRAMA\n"); break;
            case 17: printf("\t\t\t\tDEBOCHE\n"); break;
            case 18: printf("\t\t\t\tDEDAL\n"); break;
            case 19: printf("\t\t\t\tDENEGRIR\n"); break;
            case 20: printf("\t\t\t\tENXADRISTA\n"); break;
            case 21: printf("\t\t\t\tESCRIVANINHA\n"); break;
            case 22: printf("\t\t\t\tESTABILIZADOR\n"); break;
            case 23: printf("\t\t\t\tFETICHE\n"); break;
            case 24: printf("\t\t\t\tFIGO\n"); break;
            case 25: printf("\t\t\t\tFITOPLÂNCTON\n"); break;
            case 26: printf("\t\t\t\tFLAGRANTE\n"); break;
            case 27: printf("\t\t\t\tFLAMINGO\n"); break;
            case 28: printf("\t\t\t\tGENTÍLICO\n"); break;
            case 29: printf("\t\t\t\tGERGELIM\n"); break;
            case 30: printf("\t\t\t\tGRILHÃO\n"); break;
            case 31: printf("\t\t\t\tHELIPONTO\n"); break;
            case 32: printf("\t\t\t\tHIBISCO\n"); break;
            case 33: printf("\t\t\t\tHIGRÔMETRO\n"); break;
            case 34: printf("\t\t\t\tHORTÊNSIA\n"); break;
            case 35: printf("\t\t\t\tINCONSTITUCIONAL\n"); break;
            case 36: printf("\t\t\t\tITINERÁRIO\n"); break;
            case 37: printf("\t\t\t\tJANGADA\n"); break;
            case 38: printf("\t\t\t\tLACRAIA\n"); break;
            case 39: printf("\t\t\t\tLIPÍDIO\n"); break;
            case 40: printf("\t\t\t\tMASSACRE\n"); break;
            case 41: printf("\t\t\t\tMELANCÓLICO\n"); break;
            case 42: printf("\t\t\t\tMIRTILO\n"); break;
            case 43: printf("\t\t\t\tMITOCÔNDRIA\n"); break;
            case 44: printf("\t\t\t\tNITROGLICERINA\n"); break;
            case 45: printf("\t\t\t\tOBOÉ\n"); break;
            case 46: printf("\t\t\t\tOCRE\n"); break;
            case 47: printf("\t\t\t\tOPALA\n"); break;
            case 48: printf("\t\t\t\tOXIDAÇÃO\n"); break;
            case 49: printf("\t\t\t\tPARALELEPÍPEDO\n"); break;
            case 50: printf("\t\t\t\tPARLAMENTO\n"); break;
            case 51: printf("\t\t\t\tPITAYA\n"); break;
            case 52: printf("\t\t\t\tPRESCRIÇÃO\n"); break;
            case 53: printf("\t\t\t\tPROTEÍNA\n"); break;
            case 54: printf("\t\t\t\tPUBLICAÇÃO\n"); break;
            case 55: printf("\t\t\t\tPURGATÓRIO\n"); break;
            case 56: printf("\t\t\t\tQUADRAGÉSIMO\n"); break;
            case 57: printf("\t\t\t\tQUATI\n"); break;
            case 58: printf("\t\t\t\tQUEROSENE\n"); break;
            case 59: printf("\t\t\t\tQUIRERA\n"); break;
            case 60: printf("\t\t\t\tRAMAL\n"); break;
            case 61: printf("\t\t\t\tRIBOSSOMO\n"); break;
            case 62: printf("\t\t\t\tSACRILÉGIO\n"); break;
            case 63: printf("\t\t\t\tSAFADEZA\n"); break;
            case 64: printf("\t\t\t\tSUBSÍDIO\n"); break;
            case 65: printf("\t\t\t\tTEREMIN\n"); break;
            case 66: printf("\t\t\t\tTEXUGO\n"); break;
            case 67: printf("\t\t\t\tTNT\n"); break;
            case 68: printf("\t\t\t\tTRANSMISSÃO\n"); break;
            case 69: printf("\t\t\t\tTROPEÇO\n"); break;
            case 70: printf("\t\t\t\tUTOPIA\n"); break;
            case 71: printf("\t\t\t\tVÍBORA\n"); break;
            case 72: printf("\t\t\t\tXERIFE\n"); break;
            case 73: printf("\t\t\t\tSURREALISMO\n"); break;
            case 74: printf("\t\t\t\tPORCENTAGEM\n"); break;
            case 75: printf("\t\t\t\tVESPERTINO\n"); break;
            case 76: printf("\t\t\t\tMATUTINO\n"); break;
            case 77: printf("\t\t\t\tCONQUISTA\n"); break;
            case 78: printf("\t\t\t\tEGO\n"); break;
            case 79: printf("\t\t\t\tOBSCURO\n"); break;
            case 80: printf("\t\t\t\tPRINCIPADO\n"); break;
            case 81: printf("\t\t\t\tOPCIONAL\n"); break;
            case 82: printf("\t\t\t\tDIGNIDADE\n"); break;
            case 83: printf("\t\t\t\tQUALIDADE\n"); break;
            case 84: printf("\t\t\t\tINSÍGNIA\n"); break;
            case 85: printf("\t\t\t\tTRAIÇÃO\n"); break;
            case 86: printf("\t\t\t\tINVÁLIDO\n"); break;
            case 87: printf("\t\t\t\tANIL\n"); break;
            case 88: printf("\t\t\t\tCIANETO\n"); break;
            case 89: printf("\t\t\t\tANTRAZ\n"); break;
            case 90: printf("\t\t\t\tCONTEXTO\n"); break;
            case 91: printf("\t\t\t\tREQUEIJÃO\n"); break;
            case 92: printf("\t\t\t\tSAGA\n"); break;
            case 93: printf("\t\t\t\tJORNADA\n"); break;
            case 94: printf("\t\t\t\tTENENTE\n"); break;
            case 95: printf("\t\t\t\tREPARAR\n"); break;
            case 96: printf("\t\t\t\tSEMBLANTE\n"); break;
            case 97: printf("\t\t\t\tVÍNCULO\n"); break;
            case 98: printf("\t\t\t\tVISGO\n"); break;
            case 99: printf("\t\t\t\tPAUTA\n"); break;
            case 100: printf("\t\t\t\tENCOURAÇADO\n"); break;
            case 101: printf("\t\t\t\tCALIFADO\n"); break;
            case 102: printf("\t\t\t\tXÁ\n"); break;
            case 103: printf("\t\t\t\tXALE\n"); break;
            case 104: printf("\t\t\t\tPROPAROXÍTONA\n"); break;
            case 105: printf("\t\t\t\tGERÚNDIO\n"); break;
            case 106: printf("\t\t\t\tPALHETA\n"); break;
            case 107: printf("\t\t\t\tCAPOTRASTE\n"); break;
            case 108: printf("\t\t\t\tNICHO\n"); break;
            case 109: printf("\t\t\t\tVANGUARDA\n"); break;
            case 110: printf("\t\t\t\tBASTARDO\n"); break;
            case 111: printf("\t\t\t\tÁBACO\n"); break;
            case 112: printf("\t\t\t\tARREFECER\n"); break;
            case 113: printf("\t\t\t\tDEFENESTRAR\n"); break;
            case 114: printf("\t\t\t\tBAJULAR\n"); break;
            case 115: printf("\t\t\t\tMULATO\n"); break;
            case 116: printf("\t\t\t\tMESTIÇO\n"); break;
            case 117: printf("\t\t\t\tCABOCLO\n"); break;
            case 118: printf("\t\t\t\tCOINCIDÊNCIA\n"); break;
            case 119: printf("\t\t\t\tINTELECTUAL\n"); break;
            case 120: printf("\t\t\t\tCOMENSALISMO\n"); break;
            case 121: printf("\t\t\t\tATAZANAR\n"); break;
            case 122: printf("\t\t\t\tINTERMEDIÁRIO\n"); break;
            case 123: printf("\t\t\t\tNEXO\n"); break;
            case 124: printf("\t\t\t\tALMOTOLIA\n"); break;
            case 125: printf("\t\t\t\tRASURA\n"); break;
            case 126: printf("\t\t\t\tCAPACIDADE\n"); break;
            case 127: printf("\t\t\t\tANTICOAGULANTE\n"); break;
            case 128: printf("\t\t\t\tCOAGULAR\n"); break;
            case 129: printf("\t\t\t\tPERÓXIDO\n"); break;
            case 130: printf("\t\t\t\tNITROGÊNIO\n"); break;
            case 131: printf("\t\t\t\tSULFÚRICO\n"); break;
            case 132: printf("\t\t\t\tHÉLIO\n"); break;
            case 133: printf("\t\t\t\tNATIMORTO\n"); break;
            case 134: printf("\t\t\t\tLÍTIO\n"); break;
            case 135: printf("\t\t\t\tESGOELAR\n"); break;
            case 136: printf("\t\t\t\tANTICORPO\n"); break;
            case 137: printf("\t\t\t\tMERETRIZ\n"); break;
            case 138: printf("\t\t\t\tGIGOLÔ\n"); break;
            case 139: printf("\t\t\t\tFLÚOR\n"); break;
            case 140: printf("\t\t\t\tBAUXITA\n"); break;
            case 141: printf("\t\t\t\tSÍLICA\n"); break;
            case	142	:	printf("\t\t\t	BACALHAU	\n"); break;
            case	143	:	printf("\t\t\t	BÁRBARO	\n"); break;
            case	144	:	printf("\t\t\t	BETERRABA	\n"); break;
            case	145	:	printf("\t\t\t	BRASÃO	\n"); break;
            case	146	:	printf("\t\t\t	BRECHA	\n"); break;
            case	147	:	printf("\t\t\t	BRINDE	\n"); break;
            case	148	:	printf("\t\t\t	BROCHE	\n"); break;
            case	149	:	printf("\t\t\t	TRADUÇÃO	\n"); break;
            case	150	:	printf("\t\t\t	TRAMPOLIM	\n"); break;
            case	151	:	printf("\t\t\t	CAÇAROLA	\n"); break;
            case	152	:	printf("\t\t\t	CAMPEÃO	\n"); break;
            case	153	:	printf("\t\t\t	CAOS	\n"); break;
            case	154	:	printf("\t\t\t	CAPITAL	\n"); break;
            case	155	:	printf("\t\t\t	CAPRICHO	\n"); break;
            case	156	:	printf("\t\t\t	CÁPSULA	\n"); break;
            case	157	:	printf("\t\t\t	CARICATURA	\n"); break;
            case	158	:	printf("\t\t\t	CARRETEL	\n"); break;
            case	159	:	printf("\t\t\t	TRIÂNGULO	\n"); break;
            case	160	:	printf("\t\t\t	CEGONHA	\n"); break;
            case	161	:	printf("\t\t\t	CELA	\n"); break;
            case	162	:	printf("\t\t\t	CELEBRIDADE	\n"); break;
            case	163	:	printf("\t\t\t	CELULAR	\n"); break;
            case	164	:	printf("\t\t\t	DEBATE	\n"); break;
            case	165	:	printf("\t\t\t	DESCENDENTE	\n"); break;
            case	166	:	printf("\t\t\t	DETALHE	\n"); break;
            case	167	:	printf("\t\t\t	DIGESTÃO	\n"); break;
            case	168	:	printf("\t\t\t	DIPLOMATA	\n"); break;
            case	169	:	printf("\t\t\t	DISCIPLINA	\n"); break;
            case	170	:	printf("\t\t\t	DITADO	\n"); break;
            case	171	:	printf("\t\t\t	EMBAIXADOR	\n"); break;
            case	172	:	printf("\t\t\t	EMOCIONAL	\n"); break;
            case	173	:	printf("\t\t\t	EQUILÍBRIO	\n"); break;
            case	174	:	printf("\t\t\t	ESCOTEIRO	\n"); break;
            case	175	:	printf("\t\t\t	ESPERTO	\n"); break;
            case	176	:	printf("\t\t\t	ESPINHA	\n"); break;
            case	177	:	printf("\t\t\t	ESQUIMÓ	\n"); break;
            case	178	:	printf("\t\t\t	ETAPA	\n"); break;
            case	179	:	printf("\t\t\t	EXPLICAÇÃO	\n"); break;
            case	180	:	printf("\t\t\t	EXPRESSÃO	\n"); break;
            case	181	:	printf("\t\t\t	FALÊNCIA	\n"); break;
            case	182	:	printf("\t\t\t	FILTRO	\n"); break;
            case	183	:	printf("\t\t\t	FRAGÂNCIA	\n"); break;
            case	184	:	printf("\t\t\t	FRAGMENTO	\n"); break;
            case	185	:	printf("\t\t\t	FUGITIVO	\n"); break;
            case	186	:	printf("\t\t\t	FUNIL	\n"); break;
            case	187	:	printf("\t\t\t	GAVETA	\n"); break;
            case	188	:	printf("\t\t\t	GELATINA	\n"); break;
            case	189	:	printf("\t\t\t	GELEIA	\n"); break;
            case	190	:	printf("\t\t\t	GINÁSIO	\n"); break;
            case	191	:	printf("\t\t\t	GRAMPEADOR	\n"); break;
            case	192	:	printf("\t\t\t	GUARDIÃO	\n"); break;
            case	193	:	printf("\t\t\t	GUINDASTE	\n"); break;
            case	194	:	printf("\t\t\t	HÁBITO	\n"); break;
            case	195	:	printf("\t\t\t	HARÉM	\n"); break;
            case	196	:	printf("\t\t\t	HIGIENE	\n"); break;
            case	197	:	printf("\t\t\t	HONRA	\n"); break;
            case	198	:	printf("\t\t\t	VÍTIMA	\n"); break;
            case	199	:	printf("\t\t\t	VONTADE	\n"); break;
            case	200	:	printf("\t\t\t	VOZ	\n"); break;
            case	201	:	printf("\t\t\t	IMAGINAÇÃO	\n"); break;
            case	202	:	printf("\t\t\t	IMPOSSÍVEL	\n"); break;
            case	203	:	printf("\t\t\t	INDECISÃO	\n"); break;
            case	204	:	printf("\t\t\t	INDIVIDUAL	\n"); break;
            case	205	:	printf("\t\t\t	INFINITO	\n"); break;
            case	206	:	printf("\t\t\t	INFLAÇÃO	\n"); break;
            case	207	:	printf("\t\t\t	INGREDIENTE	\n"); break;
            case	208	:	printf("\t\t\t	INTERPRETAÇÃO	\n"); break;
            case	209	:	printf("\t\t\t	INTIMIDAR	\n"); break;
            case	210	:	printf("\t\t\t	INTROMETIDO	\n"); break;
            case	211	:	printf("\t\t\t	TRATOR	\n"); break;
            case	212	:	printf("\t\t\t	MOSAICO	\n"); break;
            case	213	:	printf("\t\t\t	JUDÔ	\n"); break;
            case	214	:	printf("\t\t\t	JURADO	\n"); break;
            case	215	:	printf("\t\t\t	JUVENIL	\n"); break;
            case	216	:	printf("\t\t\t	POMAR	\n"); break;
            case	217	:	printf("\t\t\t	PONTAPÉ	\n"); break;
            case	218	:	printf("\t\t\t	PORCELANA	\n"); break;
            case	219	:	printf("\t\t\t	CHAMA	\n"); break;
            case	220	:	printf("\t\t\t	CINTURA	\n"); break;
            case	221	:	printf("\t\t\t	CLOROFILA	\n"); break;
            case	222	:	printf("\t\t\t	LÃ	\n"); break;
            case	223	:	printf("\t\t\t	LAGOSTA	\n"); break;
            case	224	:	printf("\t\t\t	LANÇA	\n"); break;
            case	225	:	printf("\t\t\t	TENSÃO	\n"); break;
            case	226	:	printf("\t\t\t	VEZ	\n"); break;
            case	227	:	printf("\t\t\t	MARÉ	\n"); break;
            case	228	:	printf("\t\t\t	MARINHEIRO	\n"); break;
            case	229	:	printf("\t\t\t	MEDIEVAL	\n"); break;
            case	230	:	printf("\t\t\t	TIGELA	\n"); break;
            case	231	:	printf("\t\t\t	MINISTRO	\n"); break;
            case	232	:	printf("\t\t\t	MIRANTE	\n"); break;
            case	233	:	printf("\t\t\t	PRESSÃO	\n"); break;
            case	234	:	printf("\t\t\t	PRINCÍPIO	\n"); break;
            case	235	:	printf("\t\t\t	PROPAGANDA	\n"); break;
            case	236	:	printf("\t\t\t	COMPOSIÇÃO	\n"); break;
            case	237	:	printf("\t\t\t	COMPROMISSO	\n"); break;
            case	238	:	printf("\t\t\t	CONFERÊNCIA	\n"); break;
            case	239	:	printf("\t\t\t	CONFIDENCIAL	\n"); break;
            case	240	:	printf("\t\t\t	CONHAQUE	\n"); break;
            case	241	:	printf("\t\t\t	CONVÉS	\n"); break;
            case	242	:	printf("\t\t\t	COSTUREIRA	\n"); break;
            case	243	:	printf("\t\t\t	COUVE	\n"); break;
            case	244	:	printf("\t\t\t	CURA	\n"); break;
            case	245	:	printf("\t\t\t	PADRÃO	\n"); break;
            case	246	:	printf("\t\t\t	PASSAPORTE	\n"); break;
            case	247	:	printf("\t\t\t	PASTILHA	\n"); break;
            case	248	:	printf("\t\t\t	PASTO	\n"); break;
            case	249	:	printf("\t\t\t	PATRULHA	\n"); break;
            case	250	:	printf("\t\t\t	PAVIO	\n"); break;
            case	251	:	printf("\t\t\t	PERSONAGEM	\n"); break;
            case	252	:	printf("\t\t\t	PLATAFORMA	\n"); break;
            case	253	:	printf("\t\t\t	POETA	\n"); break;
            case	254	:	printf("\t\t\t	TALISMÃ	\n"); break;
            case	255	:	printf("\t\t\t	TANGERINA	\n"); break;
            case	256	:	printf("\t\t\t	TANGO	\n"); break;
            case	257	:	printf("\t\t\t	RAPOSA	\n"); break;
            case	258	:	printf("\t\t\t	REBOCAR	\n"); break;
            case	259	:	printf("\t\t\t	REGULAMENTO	\n"); break;
            case	260	:	printf("\t\t\t	RENDA	\n"); break;
            case	261	:	printf("\t\t\t	REPÓRTER	\n"); break;
            case	262	:	printf("\t\t\t	REVOLUÇÃO	\n"); break;
            case	263	:	printf("\t\t\t	RISOTO	\n"); break;
            case	264	:	printf("\t\t\t	RONRONAR	\n"); break;
            case	265	:	printf("\t\t\t	SABOTAGEM	\n"); break;
            case	266	:	printf("\t\t\t	SALMÃO	\n"); break;
            case	267	:	printf("\t\t\t	SANTO	\n"); break;
            case	268	:	printf("\t\t\t	SECRETÁRIA	\n"); break;
            case	269	:	printf("\t\t\t	SENSÍVEL	\n"); break;
            case	270	:	printf("\t\t\t	SIGNIFICADO	\n"); break;
            case	271	:	printf("\t\t\t	SINFONIA	\n"); break;
            case	272	:	printf("\t\t\t	SOBRENATURAL	\n"); break;
            case	273	:	printf("\t\t\t	SOCIEDADE	\n"); break;
            case	274	:	printf("\t\t\t	SUBMERSO	\n"); break;
            case	275	:	printf("\t\t\t	SUBTERRÂNEO	\n"); break;
        }
    }
    printf("\n\n\n\n");
    relogio(60);
    printf("\a");
    system("cls");
    mensagem();
}
void wait(int seconds)
{
  clock_t endwait;
  endwait = clock () + seconds * CLK_TCK;
  while (clock() < endwait) {}
}
void relogio(int tempo)
{
  int n;

  printf ("                                     fácil     médio     difícil\n");
  printf ("0s                                    40s       50s        60s\n");
  printf ("|                                      |         |         |\n");
  for (n=tempo; n>0; n--)
  {
    printf ("*");
    wait (1);
  }
}
void mensagem()
{
    system("color 4F");
    printf("\n\n\n\n\n\n");
    printf("\t\t\t||||||  ||  ||\\      //||\n\a");
    printf("\t\t\t||      ||  || \\    // ||\n\a");
    printf("\t\t\t||||||  ||  ||  \\  //  ||\n\a");
    printf("\t\t\t||      ||  ||   \\//   ||\n\a");
    printf("\t\t\t||      ||  ||         ||\n\a");
    printf("\t\t\t||      ||  ||         ||\n\a");
    printf("\n\n\n\n\n\n\n\n");
    system("pause");
    system("cls");
}



